### ISSUE TITLE
Python 3.5.2 - s3cmd still broken - follow up #987

### ISSUE THREAD

**Issue by marcinkowalczyk** [s3tools/s3cmd#1030]
Hi,

 In #987 it was mentioned, that s3cmd and IAM role for python3 should be fixed. But seems it did not happen 
s3cmd put:

```
Invoked as: /usr/local/bin/s3cmd put setup_qa.sh s3://tech/kam/
Problem: <class 'TypeError: the JSON object must be str, not 'bytes'
S3cmd:   2.0.2
python:   3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2792, in main
    cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
  File "/usr/local/lib/python3.5/dist-packages/S3/Config.py", line 245, in __init__
    self.role_config()
  File "/usr/local/lib/python3.5/dist-packages/S3/Config.py", line 266, in role_config
    creds=json.load(resp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by raghavkaul** [comment]
@marcinkowalczyk I don't think there's been a new release since the fix (5d280cb772d67e9f0c3eb79029f984b2b9815e1e) was pushed.

**Comment by WarheadsSE** [comment]
There hasn't been. I've opened #1077 specifically asking for this.

**Comment by fviard** [comment]
Release v2.1.0 with the fix is out and available in github and in Pypi.
