### ISSUE TITLE
SyntaxError: invalid syntax (_parser.py, line 477)

### ISSUE THREAD

**Issue by altmas5** [s3tools/s3cmd#1048]
Hi,

I am trying to make s3cmd run under a distro based on CentOS 6.10 (yes, I know it's a bit old).
I installed doing `pip install` and also installed using the master branch hosted on github. 
The result is the same:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd
Problem: SyntaxError: invalid syntax (_parser.py, line 477)
S3cmd:   unknown version. Module import problem?
python:   2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/s3cmd-2.0.2-py2.6.egg/EGG-INFO/scripts/s3cmd", line 3083, in <module>
    from S3.Exceptions import *
  File "/usr/lib/python2.6/site-packages/s3cmd-2.0.2-py2.6.egg/S3/Exceptions.py", line 13, in <module>
    import S3.Utils
  File "/usr/lib/python2.6/site-packages/s3cmd-2.0.2-py2.6.egg/S3/Utils.py", line 22, in <module>
    import dateutil.parser
  File "/usr/lib/python2.6/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo
  File "/usr/lib/python2.6/site-packages/dateutil/parser/_parser.py", line 477
    out = {key: self[strids[key]] for key in strids}
                                    ^
SyntaxError: invalid syntax

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I am using the following versions of the python required libs:

- python-dateutil-1.4.1-7.el6.noarch                                                                                                         
- python-magic-5.04-30.el6.x86_64
- python-six-1.9.0-2.el6.noarch
- python-setuptools-0.6.10-4.el6_9.noarch

Is it because this old version of python-dateutil is not supported?

**Comment by altmas5** [comment]
I installed the "branch-1.0.x" version and it is working for this old CentOS version.
