### ISSUE TITLE
ERROR: Test failed: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by icy** [s3tools/s3cmd#1072]
hi,

I'm using s3cmd version 2.0.2 inside a docker container. The `aws s3` command works fine, but `s3cmd` always generates errors, even during the `--configure` phase. The aws credentials are expected to be found in the ec2 metadata:

```
New settings:
  Access Key: b'foo'
  Secret Key: b'bar/3/C'
  Default Region: eu-west-1
  S3 Endpoint: s3.amazonaws.com
  DNS-style bucket+hostname:port template for accessing a bucket: %(bucket)s.s3.amazonaws.com
  Encryption password: 
  Path to GPG program: None
  Use HTTPS protocol: True
  HTTP Proxy server name: 
  HTTP Proxy server port: 0

Test access with supplied credentials? [Y/n] Y
Please wait, attempting to list all buckets...
ERROR: Test failed: can only concatenate str (not "bytes") to str

Retry configuration? [Y/n] n

Save settings? [y/N] n
Retry configuration? [Y/n] ^C
Configuration aborted. Changes were NOT saved.

```

**Comment by icy** [comment]
It seems this is because I'm using python3 instead of python2?

**Comment by icy** [comment]
More transcript

```
airflow@webserver-95ffdd5f8-4tn96:~$ s3cmd --region eu-west-1 ls s3://myops/

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd --region eu-west-1 ls s3://myops/
Problem: <class 'TypeError: can only concatenate str (not "bytes") to str
S3cmd:   2.0.2
python:   3.7.6 (default, Feb  2 2020, 09:11:24) 
[GCC 8.3.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 145, in cmd_ls
    subcmd_bucket_list(s3, uri, cfg.limit)
  File "/usr/local/bin/s3cmd", line 181, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix, limit = limit)
  File "/usr/local/lib/python3.7/site-packages/S3/S3.py", line 309, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "/usr/local/lib/python3.7/site-packages/S3/S3.py", line 343, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params, max_keys)
  File "/usr/local/lib/python3.7/site-packages/S3/S3.py", line 374, in bucket_list_noparse
    response = self.send_request(request)
  File "/usr/local/lib/python3.7/site-packages/S3/S3.py", line 1252, in send_request
    method_string, resource, headers = request.get_triplet()
  File "/usr/local/lib/python3.7/site-packages/S3/S3.py", line 201, in get_triplet
    self.sign()
  File "/usr/local/lib/python3.7/site-packages/S3/S3.py", line 197, in sign
    bucket_region, self.headers, self.body)
  File "/usr/local/lib/python3.7/site-packages/S3/Crypto.py", line 196, in sign_request_v4
    signing_key = getSignatureKey(secret_key, datestamp, region, service)
  File "/usr/local/lib/python3.7/site-packages/S3/Crypto.py", line 176, in getSignatureKey
    kDate = sign(encode_to_s3('AWS4' + key), dateStamp)
TypeError: can only concatenate str (not "bytes") to str

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by mangatmodi** [comment]
Seems related to https://github.com/s3tools/s3cmd/pull/1044

**Comment by fviard** [comment]
Are you able to reproduce this issue with the github MASTER version?
Or you just tested the 2.0.2 release version?
Thanks

**Comment by icy** [comment]
@fviard: I have tested with master and everything is fine. The problem only occurs with 2.0.2 . Thanks a lot. The issue now can be closed .

**Comment by fviard** [comment]
Thanks for your follow up. The release including this fix will come soon.
