### ISSUE TITLE
Problem: IndexError: list index out of range

### ISSUE THREAD

**Issue by jbrandru** [s3tools/s3cmd#1088]
sync fails on random files (everytime) if I use put instead of sync it works fine but that not really usable for us

```
OS: CentOS Linux release 7.6.1810 (Core)

Invoked as: /bin/s3cmd -c /XXXX/s3/.s3cfg sync /XXXX/projects/XXXX/people/XXXX/get_duration.sh s3://gm-archive/XXXX/people/XXXX/get_duration.sh
Problem: IndexError: list index out of range
S3cmd: 2.0.2 (same issue in 2.1.0)
python: 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
File "/bin/s3cmd", line 3092, in <module>
rc = main()
File "/bin/s3cmd", line 3001, in main
rc = cmd_func(args)
File "/bin/s3cmd", line 1885, in cmd_sync
return cmd_sync_local2remote(args)
File "/bin/s3cmd", line 1858, in cmd_sync_local2remote
ret = _single_process(args[:-1])
File "/bin/s3cmd", line 1612, in _single_process
return _child(destination_base, source_args)
File "/bin/s3cmd", line 1716, in _child
remote_list, dst_exclude_list, remote_total_size = fetch_remote_list(destbase_with_source_list, recursive = True, require_attribs = True)
File "/usr/lib/python2.7/site-packages/S3/FileLists.py", line 460, in fetch_remote_list
objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
File "/usr/lib/python2.7/site-packages/S3/FileLists.py", line 397, in _get_filelist_remote
recursive = recursive, uri_params = uri_params)
File "/usr/lib/python2.7/site-packages/S3/S3.py", line 309, in bucket_list
for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
File "/usr/lib/python2.7/site-packages/S3/S3.py", line 356, in bucket_list_streaming
uri_params['marker'] = current_prefixes[-1]["Prefix"]
IndexError: list index out of range
```

**Comment by fviard** [comment]
@jbrandru You have a very interesting issue. It looks like that something in the bucket_list reply is not normal in your case.
1) Are you targeting aws s3 or a another compatible service?
2) your can run your command with debug logs using the `-v -d` flags.
If you don't mind sharing the last part of the log output just before a crash, that could help me understand what reply was sent by the server to the listing and why it is not what it is expected.

Also, it could be interesting for you to have look at the files causing the crash to see if they don't have special characters.

**Comment by jbrandru** [comment]
We are targeting an internal Dell EMC ECS Object Storage

The below output has been slightly modifyed for privacy reasons (directories/hostnames)

[root@servername ~]# /bin/s3cmd -v -d -c /XXXX/.s3cfg sync /XXXX/projects/XXXX/people/XXXX/get_duration.sh s3://gm-archive/XXXX/people/XXXX/get_duration.sh
```
DEBUG: s3cmd version 2.1.0
DEBUG: ConfigParser: Reading file '/XXXX/.s3cfg'
DEBUG: ConfigParser: access_key->gm...4_chars...m
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->DK
DEBUG: ConfigParser: ca_certs_file->
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->True
DEBUG: ConfigParser: check_ssl_hostname->True
DEBUG: ConfigParser: content_disposition->
DEBUG: ConfigParser: content_type->
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/local/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->ecs.stg.domain.com:9020
DEBUG: ConfigParser: host_bucket->%(nfsbucket)s.ecs.stg.domain.com:9020
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limit->-1
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->5120
DEBUG: ConfigParser: multipart_max_chunks->10000
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: restore_priority->Standard
DEBUG: ConfigParser: secret_key->3j...37_chars...M
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: signature_v2->False
DEBUG: ConfigParser: signurl_use_https->False
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stats->False
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: throttle_max->100
DEBUG: ConfigParser: upload_id->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_http_expect->False
DEBUG: ConfigParser: use_https->False
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'sync' using UTF-8
DEBUG: Unicodising '/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Unicodising 's3://gm-archive/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Command: sync
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
INFO: No cache file found, creating it.
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
INFO: Compiling list of local files...
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Unicodising 'get_duration.sh' using UTF-8
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Unicodising '/XXXX/projects/XXXX/people/XXXX' using UTF-8
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Unicodising 'get_duration.sh' using UTF-8
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Applying --exclude/--include
DEBUG: CHECK: get_duration.sh
DEBUG: PASS: u'get_duration.sh'
INFO: Running stat() and reading/calculating MD5 values on 1 files, this may take some time...
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: doing file I/O to read md5 of get_duration.sh
DEBUG: DeUnicodising u'/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
INFO: Retrieving list of remote files for s3://gm-archive/XXXX/people/XXXX/get_duration.sh ...
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v4
DEBUG: get_hostname(gm-archive): ecs.stg.domain.com:9020
DEBUG: canonical_headers = host:ecs.stg.domain.com:9020
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200408T173523Z

DEBUG: Canonical Request:
GET
/gm-archive/
prefix=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh
host:ecs.stg.domain.com:9020
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200408T173523Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=gmrhadm/20200408/DK/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=d7991080469508bb2fb7135da6f2c931ff19f200d4dd91ca53da4f279302109b', 'x-amz-date': '20200408T173523Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(gm-archive): ecs.stg.domain.com:9020
DEBUG: ConnMan.get(): creating new connection: http://ecs.stg.domain.com:9020
DEBUG: non-proxied HTTPConnection(ecs.stg.domain.com, 9020)
DEBUG: format_uri(): /gm-archive/?prefix=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh
DEBUG: Sending request method_string='GET', uri=u'/gm-archive/?prefix=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh', headers={'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=gmrhadm/20200408/DK/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=d7991080469508bb2fb7135da6f2c931ff19f200d4dd91ca53da4f279302109b', 'x-amz-date': '20200408T173523Z'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (http://ecs.stg.domain.com:9020#1)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>gm-archive</Name><Prefix>XXXX/people/XXXX/get_duration.sh</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>true</IsTruncated><ServerSideEncryptionEnabled>false</ServerSideEncryptionEnabled><Contents><Key>XXXX/people/XXXX/get_duration.sh</Key><LastModified>2020-04-08T12:30:50.407Z</LastModified><ETag>"e5f5cbdf120709156ef09cce0819fef3"</ETag><Size>206</Size><StorageClass>STANDARD</StorageClass><Owner><ID>gmrhadm</ID><DisplayName>gmrhadm</DisplayName></Owner></Contents></ListBucketResult>',
 'headers': {'content-length': '641',
             'content-type': 'application/xml',
             'date': 'Wed, 08 Apr 2020 17:35:23 GMT',
             'server': 'ViPR/1.0',
             'x-amz-id-2': 'd5eef0f10323d9e690b608f1cfb3835d3716314ba7636e4ea00388c48a9c86c6',
             'x-amz-request-id': 'ac120043:16ee5a78a19:5e6e4:3265',
             'x-emc-retention-period': '0'},
 'reason': 'OK',
 'status': 200}
DEBUG: Listing continues after 'XXXX/people/XXXX/get_duration.sh'
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v4
DEBUG: get_hostname(gm-archive): ecs.stg.domain.com:9020
DEBUG: canonical_headers = host:ecs.stg.domain.com:9020
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200408T173524Z

DEBUG: Canonical Request:
GET
/gm-archive/
marker=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh&prefix=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh
host:ecs.stg.domain.com:9020
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200408T173524Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=gmrhadm/20200408/DK/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=8664a937d9916df6aba5d775218e79221d015fb886d62d9b2c8c4c3c6ee30e38', 'x-amz-date': '20200408T173524Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(gm-archive): ecs.stg.domain.com:9020
DEBUG: ConnMan.get(): re-using connection: http://ecs.stg.domain.com:9020#1
DEBUG: format_uri(): /gm-archive/?marker=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh&prefix=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh
DEBUG: Sending request method_string='GET', uri=u'/gm-archive/?marker=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh&prefix=XXXX%2Fpeople%2FXXXX%2Fget_duration.sh', headers={'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=gmrhadm/20200408/DK/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=8664a937d9916df6aba5d775218e79221d015fb886d62d9b2c8c4c3c6ee30e38', 'x-amz-date': '20200408T173524Z'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (http://ecs.stg.domain.com:9020#2)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>gm-archive</Name><Prefix>XXXX/people/XXXX/get_duration.sh</Prefix><Marker>XXXX/people/XXXX/get_duration.sh</Marker><MaxKeys>1000</MaxKeys><IsTruncated>true</IsTruncated><ServerSideEncryptionEnabled>false</ServerSideEncryptionEnabled></ListBucketResult>',
 'headers': {'content-length': '391',
             'content-type': 'application/xml',
             'date': 'Wed, 08 Apr 2020 17:35:24 GMT',
             'server': 'ViPR/1.0',
             'x-amz-id-2': 'd5eef0f10323d9e690b608f1cfb3835d3716314ba7636e4ea00388c48a9c86c6',
             'x-amz-request-id': 'ac120043:16ee5a78a19:5e711:2563',
             'x-emc-retention-period': '0'},
 'reason': 'OK',
 'status': 200}

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/bin/s3cmd' using UTF-8
DEBUG: Unicodising '-v' using UTF-8
DEBUG: Unicodising '-d' using UTF-8
DEBUG: Unicodising '-c' using UTF-8
DEBUG: Unicodising '/XXXX/.s3cfg' using UTF-8
DEBUG: Unicodising 'sync' using UTF-8
DEBUG: Unicodising '/XXXX/projects/XXXX/people/XXXX/get_duration.sh' using UTF-8
DEBUG: Unicodising 's3://gm-archive/XXXX/people/XXXX/get_duration.sh' using UTF-8
Invoked as: /bin/s3cmd -v -d -c /XXXX/.s3cfg sync /XXXX/projects/XXXX/people/XXXX/get_duration.sh s3://gm-archive/XXXX/people/XXXX/get_duration.sh
Problem: IndexError: list index out of range
S3cmd:   2.1.0
python:   2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/s3cmd-2.1.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 3121, in <module>
  File "/usr/lib/python2.7/site-packages/s3cmd-2.1.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 3030, in main
  File "/usr/lib/python2.7/site-packages/s3cmd-2.1.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1898, in cmd_sync
  File "/usr/lib/python2.7/site-packages/s3cmd-2.1.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1871, in cmd_sync_local2remote
  File "/usr/lib/python2.7/site-packages/s3cmd-2.1.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1625, in _single_process
  File "/usr/lib/python2.7/site-packages/s3cmd-2.1.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1729, in _child
  File "build/bdist.linux-x86_64/egg/S3/FileLists.py", line 471, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "build/bdist.linux-x86_64/egg/S3/FileLists.py", line 408, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 321, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 368, in bucket_list_streaming
    uri_params['marker'] = current_prefixes[-1]["Prefix"]
IndexError: list index out of range

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by jbrandru** [comment]
The file in the example is a simple shell script

```
FILE=$1

while read line
do
START=`cat $line | grep "^\[" | head -n1 | awk '{print $2" "$3" "$4}'`
END=`tac $line | grep "^\[" | head -n1 | awk '{print $2" "$3" "$4}'`
echo "$line,$START,$END"
done < $FILE

```

**Comment by fviard** [comment]
I could be wrong, but I think that there is an issue with the EMC ECS implementation.

```
 <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
     <Name>gm-archive</Name>
     <Prefix>XXXX/people/XXXX/get_duration.sh</Prefix>
     <Marker></Marker>
     <MaxKeys>1000</MaxKeys>
     <IsTruncated>true</IsTruncated>
     <Contents>
         <Key>XXXX/people/XXXX/get_duration.sh</Key>
         <LastModified>2020-04-08T12:30:50.407Z</LastModified>
         <ETag>"e5f5cbdf120709156ef09cce0819fef3"</ETag>
         <Size>206</Size>
     </Contents>
 </ListBucketResult>',
```
There is key `IsTruncated` that is True, when it should be False as there is just one "object" to list and so the output is not truncated.

I'm thinking if I can change the code to be able to handle such an abnormal case.

But, in the meantime, is it possible for you to do the following command:
```
/bin/s3cmd -c /XXXX/s3/.s3cfg du s3://gm-archive/XXXX/people/XXXX/
```
(So, same s3 path without the get_duration.sh at the end).
The du command should report how many files are in the same "folder" as get_duration.sh.
Alternatively, maybe you know that information already?

Then, you can try to same sync operation with the same file, but to another destination "folder" on s3 that will not have a lot of files (ie < 1000).

This is only a supposition, but I think that there is a chance that ECS is calculating the isTruncated flag with the whole folder, before noticing that it has only to send the info for 1.

**Comment by jbrandru** [comment]
The du command produces the same error but I am able to put the effected files in other "directories" 
as for number of files there are 88 files in the directory with just under 500k files in subdirectories

I have also found that the put commands also produce the error though very rarely

**Comment by fviard** [comment]
I just pushed to MASTER a fix to handle your case.
If you can, that would be great that you give it a try, otherwise it will be in next release (>= 2.2.0).

Even if it works correctly with that, it would still be better that you report the issue to Dell EMC as their behavior is not correct, and I'm afraid that it would have a side effect any day or hide something else.
(Even if I'm quite confident that normally it should work ok for you without problem except an useless extra call to listobject for nothing)

**Comment by jbrandru** [comment]
From my limited tests this seems to have resolved the issue for us 
thanks you very much
