### ISSUE TITLE
Unable to use AWS_PROFILE since upgrade to s3cmd 2.1.0

### ISSUE THREAD

**Issue by nerdyness** [s3tools/s3cmd#1094]
Hi there,

This is similar to https://github.com/s3tools/s3cmd/issues/1036 but not quite the same, so I'm raising a new issue.

Ever since upgrading to s3cmd 2.1.0 I get the following error when I try to use s3cmd without a `~/.s3cfg` present, despite having `AWS_PROFILE` and `AWS_DEFAULT_REGION` set:
```
Invoked as: /usr/local/bin/s3cmd
Problem: <class 'UnboundLocalError: local variable 'e' referenced before assignment
S3cmd:   2.1.0
python:   3.8.2 (default, Mar 11 2020, 00:28:52)
[Clang 11.0.0 (clang-1100.0.33.17)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 224, in __init__
    self.read_config_file(configfile)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 388, in read_config_file
    cp = ConfigParser(configfile)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 477, in __init__
    self.parse_file(file, sections)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 489, in parse_file
    with io.open(file, "r", encoding=self.get('encoding', 'UTF-8')) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/foo/.s3cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2818, in main
    cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 227, in __init__
    self.aws_credential_file()
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 301, in aws_credential_file
    warning("Errno %d accessing credentials file %s" % (e.errno, aws_credential_file))
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by nerdyness** [comment]
FWIW, commenting out line 301 with the missing `e` variable works for me

**Comment by fviard** [comment]
Thank you for the report.
Indeed, a typo issue.

**Comment by fviard** [comment]
That should be fixed now, I would appreciate if you could give a try to MASTER.
Thanks

**Comment by nerdyness** [comment]
>  would appreciate if you could give a try to MASTER.

I can confirm `master` is working for me 👍  Thanks for the quick turn-around!
