### ISSUE TITLE
Error syncing to S3 bucket: AttributeError: 'dict_keys' object has no attribute 'sort'

### ISSUE THREAD

**Issue by gkresic** [s3tools/s3cmd#1101]
```
Invoked as: /usr/bin/s3cmd sync . s3://lazarus/trafficsign/photo/ -P --skip-existing --acl-public --files-from=s3files
Problem: <class 'AttributeError: 'dict_keys' object has no attribute 'sort'
S3cmd:   2.1.0
python:   3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]
environment LANG=hr_HR.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1898, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/bin/s3cmd", line 1871, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/usr/bin/s3cmd", line 1625, in _single_process
    return _child(destination_base, source_args)
  File "/usr/bin/s3cmd", line 1710, in _child
    local_list, single_file_local, src_exclude_list, local_total_size = fetch_local_list(args[:-1], is_src = True, recursive = True)
  File "/usr/lib/python3/dist-packages/S3/FileLists.py", line 352, in fetch_local_list
    list_for_uri, single_file = _get_filelist_local(local_list, uri, cache)
  File "/usr/lib/python3/dist-packages/S3/FileLists.py", line 266, in _get_filelist_local
    filelist = _get_filelist_from_file(cfg, local_path)
  File "/usr/lib/python3/dist-packages/S3/FileLists.py", line 188, in _get_filelist_from_file
    keys.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

Note: I'm running this against Linode's S3-compatible ObjectStorage, but it seems unrelated to remote end, but instead as clear client/s3cmd/Python issue.

**Comment by fviard** [comment]
Thank you very much for your valuable report.
" --files-from" was causing an issue with Python3.
We should probably add a test for this option.
It is now fixed in MASTER and should be in the next release (2.2.0).
