### ISSUE TITLE
Issue while performing s3cmd sync --acl-public --reduced-redundancy --delete-removed --cf-invalidate www/* s3://domain.domain.com/web/

### ISSUE THREAD

**Issue by bhaskar-f22** [s3tools/s3cmd#1109]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd sync --acl-public --reduced-redundancy --delete-removed --cf-invalidate www/concat www/favicon.ico www/fonts www/images www/index.html www/scripts www/styles s3://patient.skymdstaging.com/web/
Problem: <class 'TypeError: Unicode-objects must be encoded before hashing
S3cmd:   2.0.2
python:   3.8.1 (default, Apr  7 2020, 12:11:58) 
[Clang 11.0.0 (clang-1100.0.33.12)]
Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1885, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/local/bin/s3cmd", line 1864, in cmd_sync_local2remote
    _invalidate_on_cf(destination_base_uri)
  File "/usr/local/bin/s3cmd", line 1834, in _invalidate_on_cf
    results = cf.InvalidateObjects(destination_base_uri, uploaded_objects_list, default_index_file, cfg.invalidate_default_index_on_cf, cfg.invalidate_default_index_root_on_cf)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/CloudFront.py", line 452, in InvalidateObjects
    cfuris = self.get_dist_name_for_bucket(uri)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/CloudFront.py", line 587, in get_dist_name_for_bucket
    response = self.GetList()
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/CloudFront.py", line 323, in GetList
    response = self.send_request("GetList")
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/CloudFront.py", line 506, in send_request
    request = self.create_request(operation, dist_id, request_id, headers)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/CloudFront.py", line 555, in create_request
    signature = self.sign_request(headers)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/CloudFront.py", line 567, in sign_request
    signature = sign_string_v2(string_to_sign)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/Crypto.py", line 68, in sign_string_v2
    signature = base64.encodestring(hmac.new(encode_to_s3(secret_key), string_to_sign, sha1).digest()).strip()
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/hmac.py", line 88, in __init__
    self.update(msg)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/hmac.py", line 96, in update
    self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3172, in <module>
    report_exception(e)
  File "/usr/local/bin/s3cmd", line 3047, in report_exception
    sys.stderr.write(u"environment LANG=%s\n" % unicodise_s(os.getenv("LANG"), 'ascii'))
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/Utils.py", line 321, in unicodise_s
    return unicodise(string, encoding, errors, True)
  File "/usr/local/Cellar/s3cmd/2.0.2_2/libexec/lib/python3.8/site-packages/S3/Utils.py", line 312, in unicodise
    return unicode(string, encoding, errors)
TypeError: decoding to str: need a bytes-like object, NoneType found
```

**Comment by fviard** [comment]
@bhaskar-f22 This issue should already be fixed in version 2.1.0. You should try to update.
