### ISSUE TITLE
s3cmd fails with error when there are no credentials in env variables

### ISSUE THREAD

**Issue by timurb** [s3tools/s3cmd#1116]
If I have no `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` defined s3cmd immediately fails with an error.
When I have those vars defined all works fine.

Also it fails even when I provide no parameters, that is when it supposed to just produce help banner and exit.

```
$ s3cmd
/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/magic.py:193: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if result is -1:

Invoked as: /usr/local/bin/s3cmd
Problem: <class 'UnboundLocalError: local variable 'e' referenced before assignment
S3cmd:   2.1.0
python:   3.8.3 (default, May 27 2020, 20:54:22)
[Clang 11.0.3 (clang-1103.0.32.59)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 224, in __init__
    self.read_config_file(configfile)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 388, in read_config_file
    cp = ConfigParser(configfile)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 477, in __init__
    self.parse_file(file, sections)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 489, in parse_file
    with io.open(file, "r", encoding=self.get('encoding', 'UTF-8')) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tbatyrshin/.s3cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2818, in main
    cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 227, in __init__
    self.aws_credential_file()
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 301, in aws_credential_file
    warning("Errno %d accessing credentials file %s" % (e.errno, aws_credential_file))
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by fviard** [comment]
Thank you for your report.
This issue is known and is normally already fixed in the current github MASTER version and should be included in the next release 2.2.0.

**Comment by fviard** [comment]
But, if possible, don't hesitate to give a try to the MASTER version to be 100% that the fix will resolve your issue.
That would be very helpful :-)

**Comment by jghaines** [comment]
Will 2.2.0 be release on pypi and brew anytime soon?
