### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment in S3/Config.py

### ISSUE THREAD

**Issue by ericlin0122** [s3tools/s3cmd#1132]
issue: https://github.com/s3tools/s3cmd/blob/v2.1.0/S3/Config.py#L301
e is not defined. 
```
Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2818, in main
    cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 227, in __init__
    self.aws_credential_file()
  File "/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/S3/Config.py", line 301, in aws_credential_file
    warning("Errno %d accessing credentials file %s" % (e.errno, aws_credential_file))
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by fviard** [comment]
Thank you for your report.
The issue has already been reported and is already fixed in the github MASTER version.
The fix will be in the next release 2.20 that will come very soon.
