### ISSUE TITLE
Can't run `s3cmd ls`

### ISSUE THREAD

**Issue by edgarjs** [s3tools/s3cmd#1146]
I just updated to 2.1.0_1 from homebrew, and now I can't run any command. I tried doing `--configure` again, and then `s3cmd ls` but no luck. I keep getting this error message:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd ls
Problem: <class 'AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
S3cmd:   2.1.0
python:   3.9.0 (default, Oct 18 2020, 02:16:06)
[Clang 12.0.0 (clang-1200.0.32.2)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 156, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/local/bin/s3cmd", line 161, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/local/Cellar/s3cmd/2.1.0_1/libexec/lib/python3.9/site-packages/S3/S3.py", line 315, in list_all_buckets
    response["list"] = getListFromXml(response["data"], "Bucket")
  File "/usr/local/Cellar/s3cmd/2.1.0_1/libexec/lib/python3.9/site-packages/S3/Utils.py", line 120, in getListFromXml
    return parseNodes(nodes)
  File "/usr/local/Cellar/s3cmd/2.1.0_1/libexec/lib/python3.9/site-packages/S3/Utils.py", line 67, in parseNodes
    for child in node.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by st-pasha** [comment]
Also, the wiki page  mentioned in the error message does not exist: https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions

**Comment by tanvir23** [comment]
I am also getting same error in my MBP. I am using MocOS Catalina 10.15.7, fi that helps

**Comment by tirkarthi** [comment]
Seems to have been fixed with https://github.com/s3tools/s3cmd/pull/1137/

**Comment by makemagik** [comment]
Having the same issue here. Is the new patch released yet? I need a fast workaround for this... Also in Catalina 10.15.7

**Comment by st-pasha** [comment]
Fast workaround is to go into the file where the error is reported and replace `for child in node.getchildren()` with  `for child in node`. Then it'll throw one other error, and you'd  have to replace I think `if child.getchildren()` with  `if list(child)`.

**Comment by makemagik** [comment]
@st-pasha you saved my life. thanks!

**Comment by fviard** [comment]
Indeed this issue is known and already fixed in MASTER.
So you can use master also.
I will release soon a new version with the fixes but a little bit more testing has still to be done to ensure that no other issue related to python 3.9.
