### ISSUE TITLE
s3cmd Errno 104 Connection reset by peer

### ISSUE THREAD

**Issue by zjs604381586** [s3tools/s3cmd#1154]
Problem: error: [Errno 104] Connection reset by peer
S3cmd:   2.0.2
python:   2.7.5 (default, Jul 13 2018, 13:06:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1887, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1475, in cmd_sync_remote2local
    ret, seq, size_transferred = _download(remote_list, seq, remote_count + update_count, size_transferred, dir_cache)
  File "/usr/bin/s3cmd", line 1321, in _download
    response = s3.object_get(uri, dst_stream, dst_file, extra_label = seq_label)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 716, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 1742, in recv_file
    data = http_response.read(this_chunk)
  File "/usr/lib64/python2.7/httplib.py", line 602, in read
    s = self.fp.read(amt)
  File "/usr/lib64/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.7/ssl.py", line 757, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 651, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 104] Connection reset by peer

**Comment by xxxchaoren** [comment]
hi I have the same problem. Have you solved your problem

**Comment by fviard** [comment]
I think that it should now be fixed in recent versions.
Please reopen if you are still encountering the issue.

**Comment by shaolila** [comment]
I have the same problem in s3cmd 2.3.0.
