### ISSUE TITLE
s3cmd crashes if a pre-existing (0 byte) cache file is used

### ISSUE THREAD

**Issue by claviola** [s3tools/s3cmd#1234]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd -c <config> --quiet --cache-file=/tmp/test.cache sync <path> s3://<bucket>/<path>/
Problem: EOFError:
S3cmd:   2.2.0
python:   2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3209, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3106, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1965, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/bin/s3cmd", line 1932, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/usr/bin/s3cmd", line 1682, in _single_process
    return _child(destination_base, source_args)
  File "/usr/bin/s3cmd", line 1772, in _child
    local_list, single_file_local, src_exclude_list, local_total_size = fetch_local_list(args[:-1], is_src = True, recursive = True)
  File "/usr/lib/python2.7/site-packages/S3/FileLists.py", line 328, in fetch_local_list
    cache.load(cfg.cache_file)
  File "/usr/lib/python2.7/site-packages/S3/HashCache.py", line 62, in load
    d = pickle.load(fp)
EOFError

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Should I actually report this at the e-mail address above? The mailing list seems overrun with spam.

**Comment by fviard** [comment]
Thank you for the PR, yes sadly the mailing list if often flooded with spam because sourceforge spam filter is not great, but we are still following it.
