### ISSUE TITLE
S3Cmd fails to put file on s3 bucket. 

### ISSUE THREAD

**Issue by justiceserv** [s3tools/s3cmd#1246]
```
root@debiannasvm:/var/disk/oc/justiceserv/files/BackUps/DownloadFileBackup# s3cmd put --recursive --progress /var/disk/oc/justiceserv/files/BackUps/DownloadFileBackup/Zoom.pkg s3://primaryprivatestorage/owncloudbackup/

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd put --recursive --progress /var/disk/oc/justiceserv/files/BackUps/DownloadFileBackup/Zoom.pkg s3://primaryprivatestorage/owncloudbackup/
Problem: <class 'KeyError: 'location'
S3cmd:   2.2.0
python:   3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/EGG-INFO/scripts/s3cmd", line 3209, in <module>
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/EGG-INFO/scripts/s3cmd", line 3106, in main
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/EGG-INFO/scripts/s3cmd", line 448, in cmd_object_put
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/S3.py", line 724, in object_put
    return self.send_file_multipart(src_stream, headers, uri, size, extra_label)
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/S3.py", line 1849, in send_file_multipart
    upload = MultiPartUpload(self, stream, uri, headers, size)
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/MultiPart.py", line 48, in __init__
    self.upload_id = self.initiate_multipart_upload()
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/MultiPart.py", line 102, in initiate_multipart_upload
    response = self.s3.send_request(request)
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/S3.py", line 1474, in send_request
    method_string, resource, headers = request.get_triplet()
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/S3.py", line 212, in get_triplet
    self.sign()
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/S3.py", line 190, in sign
    hostname = self.s3.get_hostname(self.resource['bucket'])
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/S3.py", line 283, in get_hostname
    host = getHostnameFromBucket(bucket)
  File "/usr/local/lib/python3.9/dist-packages/s3cmd-2.2.0-py3.9.egg/S3/Utils.py", line 308, in getHostnameFromBucket
    return S3.Config.Config().host_bucket.lower() % { 'bucket' : bucket }
KeyError: 'location'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
I installed s3cmd using git clone, setup.py install, which means I have latest code. 
Problem is that uploading multiple files / single file does not work while S3Cmd configuration test passed.

**Comment by justiceserv** [comment]
This operation was handled in Debian 11 BullsEye, Python 3, in KVM Machine (Although I'm not sure that's the problem).
The S3 Bucket was S3 Compatible Storage, from Wasabi
