### ISSUE TITLE
not able to configure s3cmd in Ubuntu VM

### ISSUE THREAD

**Issue by sakthivel-nunam** [s3tools/s3cmd#1250]
getting the following error while running any s3 command. 

Invoked as: /usr/bin/s3cmd ls
Problem: <class 'TypeError: can only concatenate str (not "bytes") to str
S3cmd:   2.0.2
python:   3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0]
environment LANG=C.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 149, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 154, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 302, in list_all_buckets
    response = self.send_request(request)
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 1252, in send_request
    method_string, resource, headers = request.get_triplet()
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 201, in get_triplet
    self.sign()
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 176, in sign
    self.headers = sign_request_v2(self.method_string, resource_uri, self.params, self.headers)
  File "/usr/lib/python3/dist-packages/S3/Crypto.py", line 101, in sign_request_v2
    string_to_sign += header + ":" + cur_headers[header] + "\n"
TypeError: can only concatenate str (not "bytes") to str

**Comment by fviard** [comment]
Can you update to a more recent version?
2.2.0 available on you or git MASTER
I think that this should be fixed already.

**Comment by sakthivel-nunam** [comment]
@fviard I checked with 2.2.0 it is working fine. Thaks!
