### ISSUE TITLE
Fixbucket command is broken

### ISSUE THREAD

**Issue by LadMartin** [s3tools/s3cmd#1259]
Recently I tried to use `fixbucket` on AWS to see what it does.
This is what I start with
```
$ s3cmd ls s3://mlad-test
2022-06-17 10:30            0  s3://mlad-test/foo
```
This is what I called
```
$ s3cmd fixbucket s3://mlad-test/

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd --no-ssl fixbucket s3://mlad-test/
Problem: <class 'TypeError: cannot use a string pattern on a bytes-like object
S3cmd:   2.2.0
python:   3.6.15 (default, Nov 30 2021, 03:55:20) 
[GCC 10.3.1 20211027]
environment LANG=C.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/s3cmd-2.2.0-py3.6.egg/EGG-INFO/scripts/s3cmd", line 3209, in <module>
  File "/usr/local/lib/python3.6/site-packages/s3cmd-2.2.0-py3.6.egg/EGG-INFO/scripts/s3cmd", line 3106, in main
  File "/usr/local/lib/python3.6/site-packages/s3cmd-2.2.0-py3.6.egg/EGG-INFO/scripts/s3cmd", line 2273, in cmd_fixbucket
  File "/usr/local/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Can you please verify if the command does what it suppose to do?

**Comment by fviard** [comment]
Thank you very much for the report, it should now be fixed in MASTER.
