### ISSUE TITLE
Problem: CannotSendRequest: Request-sent

### ISSUE THREAD

**Issue by ravithakkarrepo** [s3tools/s3cmd#1261]
Invoked as: /usr/local/bin/s3cmd --configure
Problem: CannotSendRequest: Request-sent
S3cmd:   2.2.0
python:   3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
environment LANG=en_IN

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/s3cmd-2.2.0-py3.8.egg/EGG-INFO/scripts/s3cmd", line 3209, in <module>
  File "/usr/local/lib/python3.8/dist-packages/s3cmd-2.2.0-py3.8.egg/EGG-INFO/scripts/s3cmd", line 2895, in main
  File "/usr/local/lib/python3.8/dist-packages/s3cmd-2.2.0-py3.8.egg/S3/Config.py", line 289, in __init__
    self.role_config()
  File "/usr/local/lib/python3.8/dist-packages/s3cmd-2.2.0-py3.8.egg/S3/Config.py", line 383, in role_config
    conn.request('GET', "/latest/meta-data/iam/security-credentials/", headers=imds_auth)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/dist-packages/s3cmd-2.2.0-py3.8.egg/S3/Custom_httplib3x.py", line 159, in httpconnection_patched_send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.8/http/client.py", line 1093, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent

**Comment by fviard** [comment]
Hi,
I have just pushed in MASTER a fix for this issue, could it be possible for you to give it a try?
If it works, I will try to have a release soon with that.
Thank you
