### ISSUE TITLE
Problem: http.client.ResponseNotReady: Request-sent

### ISSUE THREAD

**Issue by kuzaxak** [s3tools/s3cmd#1263]
Version: latest master

```
17:33:30
17:33:30  Invoked as: /usr/bin/s3cmd sync --no-delete-removed --no-preserve --follow-symlinks --no-mime-magic --no-progress --include docs/images/phone_number_edit_220701.png docs/images/ s3://docs-img.glia.com/images/
17:33:30  Problem: ResponseNotReady: Request-sent
17:33:30  S3cmd:   2.2.0
17:33:30  python:   3.9.2 (default, Feb 28 2021, 17:03:44)
17:33:30  [GCC 10.2.1 20210110]
17:33:30  environment LANG=NOTSET
17:33:30
17:33:30  Traceback (most recent call last):
17:33:30    File "/usr/bin/s3cmd", line 3210, in <module>
17:33:30      rc = main()
17:33:30    File "/usr/bin/s3cmd", line 2896, in main
17:33:30      cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
17:33:30    File "/opt/s3cmd/S3/Config.py", line 289, in __init__
17:33:30      self.role_config()
17:33:30    File "/opt/s3cmd/S3/Config.py", line 385, in role_config
17:33:30      resp = conn.getresponse()
17:33:30    File "/usr/lib/python3.9/http/client.py", line 1337, in getresponse
17:33:30      raise ResponseNotReady(self.__state)
17:33:30  http.client.ResponseNotReady: Request-sent
```

**Comment by kuzaxak** [comment]
Seems like we have an issue after [commit][1] was merged

[1]: https://github.com/s3tools/s3cmd/commit/3d3ac4a4099446cbc2ff6ec97feb46f2936bf5d5

**Comment by fviard** [comment]
@kuzaxak A fix for this issue was pushed in master a few days ago. Could you give a try to MASTER with it?
Otherwise, there should be a release with it soon.

**Comment by kuzaxak** [comment]
We have this issue on latest master.

**Comment by fviard** [comment]
@kuzaxak Thank you very much for your report, in fact there was a typo in the previous fix and a too wide "try/catch" is masking the issue.

I just pushed a new change to MASTER to really fix this issue, if you could confirm me that it works for you, it would be great.
Thanks
