### ISSUE TITLE
Connection Reset error doesn't automatically retry

### ISSUE THREAD

**Issue by swrobel** [s3tools/s3cmd#1285]
I was under the impression that connection reset errors would automatically retry, but instead my days-long header modification task just failed and exited in the middle.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: ./s3cmd modify --recursive --add-header=Cache-Control: public, max-age=31536000, immutable s3://my-bucket
Problem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer
S3cmd:   2.3.0
python:   3.7.10 (default, Jun  3 2021, 00:01:07)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 3286, in <module>
    rc = main()
  File "./s3cmd", line 3183, in main
    rc = cmd_func(args)
  File "./s3cmd", line 983, in cmd_modify
    u"modify: '%(src)s'  %(extra)s")
  File "./s3cmd", line 956, in subcmd_cp_mv
    extra_label=seq_label)
  File "/home/ec2-user/s3cmd-2.3.0/S3/S3.py", line 1013, in object_modify
    extra_label, replace_meta=True)
  File "/home/ec2-user/s3cmd-2.3.0/S3/S3.py", line 1001, in object_copy
    self.set_acl(dst_uri, acl)
  File "/home/ec2-user/s3cmd-2.3.0/S3/S3.py", line 1071, in set_acl
    response = self.send_request(request)
  File "/home/ec2-user/s3cmd-2.3.0/S3/S3.py", line 1520, in send_request
    conn.c.request(method_string, uri, request.body, headers)
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ec2-user/s3cmd-2.3.0/S3/Custom_httplib3x.py", line 199, in httpconnection_patched_send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ec2-user/s3cmd-2.3.0/S3/Custom_httplib3x.py", line 225, in httpconnection_patched_endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ec2-user/s3cmd-2.3.0/S3/Custom_httplib3x.py", line 256, in httpconnection_patched_send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

$ ./s3cmd --version
s3cmd version 2.3.0
```

**Comment by fviard** [comment]
Your issue is very strange. There is indeed a code to retry for that in theory.

Is this reproducible for you? if yes, you could run s3cmd with the --debug flag to have more details.

**Comment by yarikoptic** [comment]
FWIW -- just ran into likely the same on debian system

```
s3cmd:
  Installed: 2.4.0-3
  Candidate: 2.4.0-3
  Version table:
 *** 2.4.0-3 500
        500 http://deb.debian.org/debian trixie/main amd64 Packages
        100 /var/lib/dpkg/status
```

invocation in cron (it was disabled for awhile and without note why was disabled, heh) 

```
chronic flock -E 0 -e -n /home/dandi/.run/manifests-update-s3cmd.lock s3cmd -c ~/.s3cfg-dandi-backup-2 sync s3://dandiarchive/dandisets/ /mnt/backup/dandi/dandiset-manifests-s3cmd/ 
````

<details>
<summary>full output</summary> 

```shell
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                                                                                                                                                                                                                                                                                                                                           
    An unexpected error has occurred.                                                                                                                                                                                                                                                                                                                                                                                                                               
  Please try reproducing the error using                                                                                                                                                                                                                                                                                                                                                                                                                            
  the latest s3cmd code from the git master                                                                                                                                                                                                                                                                                                                                                                                                                         
  branch found at:                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    https://github.com/s3tools/s3cmd                                                                                                                                                                                                                                                                                                                                                                                                                                
  and have a look at the known issues list:                                                                                                                                                                                                                                                                                                                                                                                                                         
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)                                                                                                                                                                                                                                                                                                                                                                             
  If the error persists, please report the                                                                                                                                                                                                                                                                                                                                                                                                                          
  following lines (removing any private                                                                                                                                                                                                                                                                                                                                                                                                                             
  info as necessary) to:                                                                                                                                                                                                                                                                                                                                                                                                                                            
   s3tools-bugs@lists.sourceforge.net                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Invoked as: /usr/bin/s3cmd -c /home/dandi/.s3cfg-dandi-backup-2 sync s3://dandiarchive/dandisets/ /mnt/backup/dandi/dandiset-manifests-s3cmd/                                                                                                                                                                                                                                                                                                                       
Problem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer                                                                                                                                                                                                                                                                                                                                                                                         
S3cmd:   2.4.0                                                                                                                                                                                                                                                                                                                                                                                                                                                      
python:   3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0]                                                                                                                                                                                                                                                                                                                                                                                                         
environment LANG=en_US.UTF-8                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                  
  File "/usr/bin/s3cmd", line 3627, in <module>                                                                                                                                                                                                                                                                                                                                                                                                                     
    rc = main()                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  File "/usr/bin/s3cmd", line 3524, in main                                                                                                                                                                                                                                                                                                                                                                                                                         
    rc = cmd_func(args)                                                                                                                                                                                                                                                                                                                                                                                                                                             
  File "/usr/bin/s3cmd", line 2163, in cmd_sync                                                                                                                                                                                                                                                                                                                                                                                                                     
    return cmd_sync_remote2local(args)                                                                                                                                                                                                                                                                                                                                                                                                                              
  File "/usr/bin/s3cmd", line 1362, in cmd_sync_remote2local                                                                                                                                                                                                                                                                                                                                                                                                        
    remote_list, src_exclude_list, remote_total_size = fetch_remote_list(fetch_source_args, recursive = True, require_attribs = True)                                                                                                                                                                                                                                                                                                                               
                                                       ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                               
  File "/usr/lib/python3/dist-packages/S3/FileLists.py", line 515, in fetch_remote_list                                                                                                                                                                                                                                                                                                                                                                             
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)                                                                                                                                                                                                                                                                                                                                                                                        
                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3/dist-packages/S3/FileLists.py", line 442, in _get_filelist_remote                                                                                                                                                                                                                                                                                                                                                                          
    response = s3.bucket_list(remote_uri.bucket(), prefix = remote_uri.object(),                                                                                                                                                                                                                                                                                                                                                                                    
                              recursive = recursive, uri_params = uri_params)                                                                                                                                                                                                                                                                                                                                                                                       
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 323, in bucket_list                                                                                                                                                                                                                                                                                                                                                                                          
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):                                                                                                                                                                                                                                                                                                                                                       
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 357, in bucket_list_streaming                                                                                                                                                                                                                                                                                                                                                                                
    response = self.bucket_list_noparse(bucket, prefix, recursive,                                                                                                                                                                                                                                                                                                                                                                                                  
                                        uri_params, max_keys)                                                                                                                                                                                                                                                                                                                                                                                                       
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 398, in bucket_list_noparse                                                                                                                                                                                                                                                                                                                                                                                  
    response = self.send_request(request)                                                                                                                                                                                                                                                                                                                                                                                                                           
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 1707, in send_request                                                                                                                                                                                                                                                                                                                                                                                        
    conn = ConnMan.get(self.get_hostname(resource['bucket']))                                                                                                                                                                                                                                                                                                                                                                                                       
  File "/usr/lib/python3/dist-packages/S3/ConnMan.py", line 288, in get                                                                                                                                                                                                                                                                                                                                                                                             
    conn.c.connect()                                                                                                                                                                                                                                                                                                                                                                                                                                                
    ~~~~~~~~~~~~~~^^                                                                                                                                                                                                                                                                                                                                                                                                                                                
  File "/usr/lib/python3.13/http/client.py", line 1479, in connect                                                                                                                                                                                                                                                                                                                                                                                                  
    self.sock = self._context.wrap_socket(self.sock,                                                                                                                                                                                                                                                                                                                                                                                                                
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                
                                          server_hostname=server_hostname)                                                                                                                                                                                                                                                                                                                                                                                          
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                          
  File "/usr/lib/python3.13/ssl.py", line 455, in wrap_socket                                                                                                                                                                                                                                                                                                                                                                                                       
    return self.sslsocket_class._create(                                                                                                                                                                                                                                                                                                                                                                                                                            
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^                                                                                                                                                                                                                                                                                                                                                                                                                            
        sock=sock,                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        ^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    ...<5 lines>...                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        session=session                                                                                                                                                                                                                                                                                                                                                                                                                                             
        ^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                                             
    )                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    ^                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  File "/usr/lib/python3.13/ssl.py", line 1076, in _create                                                                                                                                                                                                                                                                                                                                                                                                          
    self.do_handshake()                                                                                                                                                                                                                                                                                                                                                                                                                                             
    ~~~~~~~~~~~~~~~~~^^                                                                                                                                                                                                                                                                                                                                                                                                                                             
  File "/usr/lib/python3.13/ssl.py", line 1372, in do_handshake                                                                                                                                                                                                                                                                                                                                                                                                     
    self._sslobj.do_handshake()                                                                                                                                                                                                                                                                                                                                                                                                                                     
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^                                                                                                                                                                                                                                                                                                                                                                                                                                     
ConnectionResetError: [Errno 104] Connection reset by peer                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                                                                                                                                                                                                                                                                                                                                           
    An unexpected error has occurred.                                                                                                                                                                                                                                                                                                                                                                                                                               
  Please try reproducing the error using                                                                                                                                                                                                                                                                                                                                                                                                                            
  the latest s3cmd code from the git master                                                                                                                                                                                                                                                                                                                                                                                                                         
  branch found at:                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    https://github.com/s3tools/s3cmd                                                                                                                                                                                                                                                                                                                                                                                                                                
  and have a look at the known issues list:                                                                                                                                                                                                                                                                                                                                                                                                                         
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)                                                                                                                                                                                                                                                                                                                                                                             
  If the error persists, please report the                                                                                                                                                                                                                                                                                                                                                                                                                          
  above lines (removing any private                                                                                                                                                                                                                                                                                                                                                                                                                                 
  info as necessary) to:                                                                                                                                                                                                                                                                                                                                                                                                                                            
   s3tools-bugs@lists.sourceforge.net                                                                                                                                                                                                                                                                                                                                                                                                                               
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        
```
</details>

will rerun now with --debug as requested above

**Comment by yarikoptic** [comment]
oh, that wasn't fun -- too quickly it completed and without fails, here is our [`duct`](https://github.com/con/duct) summary FTR (so I could find later if needed)

```
dandi@drogon:/mnt/backup/dandi/dandiset-manifests-s3cmd$ con-duct ls
PREFIX                                  COMMAND                                                                                                                                                 EXIT_CODE WALL_CLOCK_TIME PEAK_RSS
.duct/logs/2026.04.15T09.18.09-2097507_ flock -E 0 -e -n /home/dandi/.run/manifests-update-s3cmd.lock s3cmd -c /home/dandi/.s3cfg-dandi-backup-2 --debug sync s3://dandiarchive/dandisets/ /... 0         15.840 sec      66.0 MB
```
