### ISSUE TITLE
S3 fails to load files (rare occurance)

### ISSUE THREAD

**Issue by charlescurt** [s3tools/s3cmd#1303]
I am streaming data into multiple machine learning models training on GPU. The data throughput is sufficient. However, I get an occasional error from this. I only started noticing these issues when the model data needed increasing. I have previously trained 1000+ models simultaneously without incident but on smaller datasets.

For context, I am not sharing data between the models, and they each have their own files to be streamed in. I am however, sharing the same bucket.

I believe this is an S3 limitation. I do not know what that limitation is, so if someone knows a single bucket's limits, please let me know!

<img width="311" alt="Screen Shot 2023-01-24 at 9 58 19 AM" src="https://user-images.githubusercontent.com/98784768/214371341-350db5f4-6b09-4ac7-95ae-089089f0caa1.png">

```
WARNING: Retrying failed request: myfilepath.tar (EOF from S3!)
WARNING: Waiting 3 sec...
```

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/conda/bin/s3cmd get s3://myfilepath.tar -
Problem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer
S3cmd:   2.2.0
python:   3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0]
environment LANG=NOTSET

Traceback (most recent call last):
  File "/opt/conda/bin/s3cmd", line 3209, in <module>
    rc = main()
  File "/opt/conda/bin/s3cmd", line 3106, in main
    rc = cmd_func(args)
  File "/opt/conda/bin/s3cmd", line 621, in cmd_object_get
    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)
  File "/opt/conda/lib/python3.7/site-packages/S3/S3.py", line 763, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "/opt/conda/lib/python3.7/site-packages/S3/S3.py", line 1975, in recv_file
    data = http_response.read(this_chunk)
  File "/opt/conda/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
  File "/opt/conda/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
  File "/opt/conda/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/conda/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/conda/bin/s3cmd get s3://myfilepath.tar -
Problem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer
S3cmd:   2.2.0
python:   3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0]
environment LANG=NOTSET

Traceback (most recent call last):
  File "/opt/conda/bin/s3cmd", line 3209, in <module>
    rc = main()
  File "/opt/conda/bin/s3cmd", line 3106, in main
    rc = cmd_func(args)
  File "/opt/conda/bin/s3cmd", line 621, in cmd_object_get
    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)
  File "/opt/conda/lib/python3.7/site-packages/S3/S3.py", line 763, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "/opt/conda/lib/python3.7/site-packages/S3/S3.py", line 1975, in recv_file
    data = http_response.read(this_chunk)
  File "/opt/conda/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
  File "/opt/conda/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
  File "/opt/conda/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/conda/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  #mycode#
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
Exception: Caught Exception in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/opt/conda/lib/python3.7/site-packages/webdataset/pipeline.py", line 68, in iterator
    for sample in self.iterator1():
  File "/opt/conda/lib/python3.7/site-packages/webdataset/filters.py", line 388, in _to_tuple
    for sample in data:
  File "/opt/conda/lib/python3.7/site-packages/webdataset/filters.py", line 293, in _map
    for sample in data:
  File "/opt/conda/lib/python3.7/site-packages/webdataset/filters.py", line 204, in _shuffle
    for sample in data:
  File "/opt/conda/lib/python3.7/site-packages/webdataset/tariterators.py", line 152, in group_by_keys
    for filesample in data:
  File "/opt/conda/lib/python3.7/site-packages/webdataset/tariterators.py", line 139, in tar_file_expander
    if handler(exn):
  File "/opt/conda/lib/python3.7/site-packages/webdataset/filters.py", line 76, in reraise_exception
    raise exn
  File "/opt/conda/lib/python3.7/site-packages/webdataset/tariterators.py", line 131, in tar_file_expander
    for sample in tar_file_iterator(source["stream"]):
  File "/opt/conda/lib/python3.7/site-packages/webdataset/tariterators.py", line 114, in tar_file_iterator
    if handler(exn):
  File "/opt/conda/lib/python3.7/site-packages/webdataset/handlers.py", line 23, in reraise_exception
    raise exn
  File "/opt/conda/lib/python3.7/site-packages/webdataset/tariterators.py", line 107, in tar_file_iterator
    data = stream.extractfile(tarinfo).read()
  File "/opt/conda/lib/python3.7/tarfile.py", line 695, in read
    b = self.fileobj.read(length)
  File "/opt/conda/lib/python3.7/tarfile.py", line 537, in read
    buf = self._read(size)
  File "/opt/conda/lib/python3.7/tarfile.py", line 545, in _read
    return self.__read(size)
  File "/opt/conda/lib/python3.7/tarfile.py", line 570, in __read
    buf = self.fileobj.read(self.bufsize)
  File "/opt/conda/lib/python3.7/site-packages/webdataset/gopen.py", line 86, in read
    self.check_status()
  File "/opt/conda/lib/python3.7/site-packages/webdataset/gopen.py", line 66, in check_status
    self.wait_for_child()
  File "/opt/conda/lib/python3.7/site-packages/webdataset/gopen.py", line 81, in wait_for_child
    raise Exception(f"{self.args}: exit {self.status} (read) {info}")
Exception: ("(('s3cmd get s3://myfilepath.tar -',), {'shell': True, 'bufsize': 8192}): exit 74 (read) {} @ <Pipe (('s3cmd get s3://myfilepath.tar -',), {'shell': True, 'bufsize': 8192})>", <webdataset.gopen.Pipe object at 0x7fb7dfaac6d0>, 'pipe:s3cmd get s3://myfilepath.tar -')
```

**Comment by charlescurt** [comment]
Seemingly the same or similar issue: https://github.com/s3tools/s3cmd/issues/1285
