### ISSUE TITLE
Linode Owncast install - bucket_policy.json error parsing xml: not well-formed (invalid token) line 1, column 3

### ISSUE THREAD

**Issue by WetYeti** [s3tools/s3cmd#1320]
Creating a file called bucket_policy.json that has the following:

   {
   "Statement": [
   {
   "Effect": "Allow",
   "Principal": {
   "AWS": [
   "*"
   ]
   },
   "Action": [
   "s3:GetObject"
   ],
   "Resource": [
   "arn:aws:s3::MYBUCKETNAME/*"
   ]
   }
   ]
   }
   
and viewing the info using s3cmd info s3://MYBUCKETNAME pops 
ERROR: Error parsing xml: not well-formed (invalid token): line 1, column 3
ERROR:    {
   "Statement": [
   {
   "Effect": "Allow",
   "Principal": {
   "AWS": [
   "*"
   ]
   },
   "Action": [
   "s3:GetObject"
   ],
   "Resource": [
   "arn:aws:s3::MYBUCKETNAME/*"
   ]
   }
   ]
   }

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd info s3://MYBUCKETNAME
Problem: ParseError: not well-formed (invalid token): line 1, column 3
S3cmd:   2.3.0-dev
python:   2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.3.0.dev0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 3461, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.3.0.dev0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 3358, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.3.0.dev0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1079, in cmd_info
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 473, in bucket_info
    response['bucket-location'] = self.get_bucket_location(uri)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 453, in get_bucket_location
    location = getTextFromXml(response['data'], "LocationConstraint")
  File "build/bdist.linux-x86_64/egg/S3/BaseUtils.py", line 324, in getTextFromXml
    tree = getTreeFromXml(xml)
  File "build/bdist.linux-x86_64/egg/S3/BaseUtils.py", line 286, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 3

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by WetYeti** [comment]
https://www.linode.com/docs/products/storage/object-storage/guides/s3cmd/ "even with error"
