### ISSUE TITLE
Problem: <class 'NameError: name 'formatDateTime' is not defined

### ISSUE THREAD

**Issue by saeed-raeisi** [s3tools/s3cmd#1344]
> Invoked as: /usr/bin/s3cmd ls
> Problem: <class 'NameError: name 'formatDateTime' is not defined
> S3cmd:   2.3.0
> python:   3.8.10 (default, May 26 2023, 14:05:08) 
> [GCC 9.4.0]
> environment LANG=C.UTF-8

```
Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 149, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 157, in subcmd_all_buckets_list
    output(u"%s  s3://%s" % (formatDateTime(bucket["CreationDate"]),
NameError: name 'formatDateTime' is not defined
```

> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>     An unexpected error has occurred.
>   Please try reproducing the error using
>   the latest s3cmd code from the git master
>   branch found at:
>     https://github.com/s3tools/s3cmd
>   and have a look at the known issues list:
>     https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
>   If the error persists, please report the
>   above lines (removing any private
>   info as necessary) to:
>    s3tools-bugs@lists.sourceforge.net
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by saeed-raeisi** [comment]
Invoked as: /usr/bin/s3cmd ls
Problem: <class 'NameError: name 'formatDateTime' is not defined
S3cmd:   2.3.0
python:   3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
environment LANG=C.UTF-8


OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-164-generic


when install this version : pip3 install s3cmd==2.1.0
in s3cmd put
ERROR:
^CTraceback (most recent call last):
  File "/usr/bin/s3cmd", line 58, in <module>
    from optparse import OptionParser, Option, OptionValueError, IndentedHelpFormatter
  File "/usr/lib/python3.8/optparse.py", line 90, in <module>
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/local/lib/python3.8/dist-packages/S3/S3.py", line 687, in object_put
    return self.send_file_multipart(src_stream, headers, uri, size, extra_label)
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 421, in cmd_object_put
    response = s3.object_put(full_name, uri_final, extra_headers, extra_label = seq_label)
  File "/usr/local/lib/python3.8/dist-packages/S3/S3.py", line 687, in object_put
    return self.send_file_multipart(src_stream, headers, uri, size, extra_label)
  File "/usr/local/lib/python3.8/dist-packages/S3/S3.py", line 1613, in send_file_multipart
    upload.upload_all_parts(extra_label)
  File "/usr/local/lib/python3.8/dist-packages/S3/MultiPart.py", line 119, in upload_all_parts
    self.upload_part(seq, offset, current_chunk_size, labels, remote_status = remote_statuses.get(seq))
  File "/usr/local/lib/python3.8/dist-packages/S3/MultiPart.py", line 176, in upload_part
    response = self.s3.send_file(request, self.file_stream, labels, buffer, offset = offset, chunk_size = chunk_size)
  File "/usr/local/lib/python3.8/dist-packages/S3/S3.py", line 1551, in send_file
    return self._http_403_handler(request, response,
  File "/usr/local/lib/python3.8/dist-packages/S3/S3.py", line 1228, in _http_403_handler
    failureCode = getTextFromXml(response['data'], 'Code')
  File "/usr/local/lib/python3.8/dist-packages/S3/Utils.py", line 142, in getTextFromXml
    tree = getTreeFromXml(xml)
  File "/usr/local/lib/python3.8/dist-packages/S3/Utils.py", line 106, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the

**Comment by fviard** [comment]
@saeed-raeisi Can you install the last MASTER version, a fix for this issue was pushed recently and is not yet in a release.

**Comment by saeed-raeisi** [comment]
this error:
```
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2
```

my s3 provider([object-storage](https://parspack.com/cloud-storage)) return 403 because max limit of traffic
after paid problem is solved
