### ISSUE TITLE
Wrapper script to utilize AWS SSO - getting strange error

### ISSUE THREAD

**Issue by jasonreevessimmons** [s3tools/s3cmd#1345]
Hello,

I created a wrapper script that uses the AWS CLI to handle SSO logins, and then gets the necessary bits out to feed to `s3cmd`.  Here's the script:
```
#!/bin/bash


export AWS_PROFILE=$1
aws sts get-caller-identity
if [ "$?" -ne "0" ]
then
  echo "Logging you in to profile [$AWS_PROFILE]"
  aws sso login
else
  echo "You are logged in to [$AWS_PROFILE] with the account above"
fi

aws_cache_dir="$HOME/.aws/sso/cache/"
token_file=`ls -rt $aws_cache_dir | tail -1`
export AWS_REGION=`cat $aws_cache_dir/$token_file | jq -r ".region"`
access_token=`cat $aws_cache_dir/$token_file | jq -r ".accessToken"`
caller_identity=`aws sts get-caller-identity`

account_id=`echo "$caller_identity" | jq -r ".Account"`
role_name=`echo "$caller_identity" | jq -r ".Arn" | cut -d_ -f2`

real_s3cmd="/opt/homebrew/Cellar/s3cmd/2.3.0/bin/s3cmd"

role_credentials=`aws sso get-role-credentials \
  --account-id $account_id \
  --role-name $role_name \
  --access-token $access_token`

AWS_ACCESS_KEY_ID=`echo "$role_credentials" | jq -r ".roleCredentials.accessKeyId"`
AWS_SECRET_ACCESS_KEY=`echo "$role_credentials" | jq -r ".roleCredentials.secretAccessKey"`
AWS_SESSION_TOKEN=`echo "$role_credentials" | jq -r ".roleCredentials.sessionToken"`

echo $role_credentials | jq "."

$real_s3cmd \
  --access_key=$AWS_ACCESS_KEY_ID \
  --secret_key=$AWS_SECRET_ACCESS_KEY \
  --access_token=$AWS_SESSION_TOKEN \
  --dump-config > ~/.s3cfg

$real_s3cmd ls
```

The command `s3cmd --version` reveals I am using version 2.3.0 of the tool.

My `uname -a` gives this output:
```
Darwin admins-MBP.home 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
```

I installed `s3cmd` with `brew install s3cmd`.

And finally, here is the error message I am getting when trying to run `s3cmd ls`:
```WARNING: Could not refresh role

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Invoked as: /opt/homebrew/bin/s3cmd ls
Problem: <class 'TypeError: sequence item 1: expected str instance, bytes found
S3cmd:   2.3.0
python:   3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/opt/homebrew/bin/s3cmd", line 3286, in <module>
    rc = main()
         ^^^^^^
  File "/opt/homebrew/bin/s3cmd", line 3183, in main
    rc = cmd_func(args)
         ^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/s3cmd", line 171, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/opt/homebrew/bin/s3cmd", line 176, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/s3cmd/2.3.0/libexec/lib/python3.12/site-packages/S3/S3.py", line 327, in list_all_buckets
    response["list"] = getListFromXml(response["data"], "Bucket")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/s3cmd/2.3.0/libexec/lib/python3.12/site-packages/S3/BaseUtils.py", line 277, in getListFromXml
    tree = getTreeFromXml(xml)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/s3cmd/2.3.0/libexec/lib/python3.12/site-packages/S3/BaseUtils.py", line 263, in getTreeFromXml
    xml, xmlns = stripNameSpace(encode_to_s3(xml))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/s3cmd/2.3.0/libexec/lib/python3.12/site-packages/S3/BaseUtils.py", line 255, in stripNameSpace
    xml = RE_XML_NAMESPACE.sub("\\1\\2", xml, 1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, bytes found

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Please advise.  Thanks!

**Comment by jasonreevessimmons** [comment]
I'm very close to my goal with this script.  

When I run the `s3cmd` program with `--debug` - I can see that the XML containing my list of buckets is actually being returned by AWS.  By the time `BaseUtils.py` needs to do some regular expression magic, the XML is supposed to have been converted to a string, but it is still an array of bytes.

**Comment by jasonreevessimmons** [comment]
Running my script within a Linux-based Docker container works.

The `uname -a` for the Docker container:
```
Linux 0f9552b29a46 6.5.6-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:34:05 UTC 2023 x86_64 GNU/Linux
```

So this is likely a dependency issue either having to do with `brew` or with MacOS.

**Comment by jasonreevessimmons** [comment]
If anyone is interested in using the wrapper scripts, just remove the last command and replace it with:
```
shift ## get the profile off the stack
$real_s3cmd $@ 2>&1 | grep -v "^WARNING: Could not refresh role"
```

Then you can use `s3cmd.sh <profile_name> s3arg1 s3arg2 ... s3argN` to call `s3cmd` and interact with it using the given profile.

**Comment by jasonreevessimmons** [comment]
Full script:

```
#!/bin/bash

export AWS_PROFILE=$1
aws sts get-caller-identity --profile $AWS_PROFILE
if [ "$?" -ne "0" ]
then
  echo "Logging you in to profile [$AWS_PROFILE]"
  aws sso login --profile $AWS_PROFILE
else
  echo "You are logged in to [$AWS_PROFILE] with the account above"
fi


aws_cache_dir="$HOME/.aws/sso/cache"
token_file=`ls -rt $aws_cache_dir | tail -1`
export AWS_REGION=`cat $aws_cache_dir/$token_file | jq -r ".region"`
access_token=`cat $aws_cache_dir/$token_file | jq -r ".accessToken"`
caller_identity=`aws sts get-caller-identity --profile $AWS_PROFILE`

account_id=`echo "$caller_identity" | jq -r ".Account"`
role_name=`echo "$caller_identity" | jq -r ".Arn" | cut -d_ -f2`

real_s3cmd="/opt/homebrew/Cellar/s3cmd/2.3.0/bin/s3cmd"

role_credentials=`aws sso get-role-credentials \
  --account-id $account_id \
  --role-name $role_name \
  --access-token $access_token`

AWS_ACCESS_KEY_ID=`echo "$role_credentials" | jq -r ".roleCredentials.accessKeyId"`
AWS_SECRET_ACCESS_KEY=`echo "$role_credentials" | jq -r ".roleCredentials.secretAccessKey"`
AWS_SESSION_TOKEN=`echo "$role_credentials" | jq -r ".roleCredentials.sessionToken"`

echo $role_credentials | jq "."

$real_s3cmd \
  --access_key=$AWS_ACCESS_KEY_ID \
  --secret_key=$AWS_SECRET_ACCESS_KEY \
  --access_token=$AWS_SESSION_TOKEN \
  --dump-config > ~/.s3cfg

shift ## get the profile off the stack
$real_s3cmd $@ 2>&1 | grep -v "^WARNING: Could not refresh role"
```

**Comment by fviard** [comment]
Your original bug is related to an issue with python 3.12 that is totally not related with what you try to do.
Please try again with the MASTER version of s3cmd before the next version is released. (As a fix for this issue was already pushed).

**Comment by fviard** [comment]
FYI, the version v2.4.0 is now released with the right correction.
