### ISSUE TITLE
`TypeError` with Minio when using `la` or `ls`

### ISSUE THREAD

**Issue by The-Judge** [s3tools/s3cmd#1357]
I created a very basic Minio using Docker locally on my machine. This is the `docker-compose.yml`:

```yaml
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - app-tier
```

I am using the newest s3cmd available as of the time of this writing on my Mac, installed using Homebrew:

```shell
❯ s3cmd --version
s3cmd version 2.3.0
```

I tried to make (`mb`) and remove (`rb`) buckets and to `put`/`get`/`del` files; all are working.
As soon as I am using `la` or `lb`, I am hit by this error:

```shell
❯ s3cmd --no-progress --stats --verbose --access_key=***REMOVED*** --secret_key=***REMOVED*** --host="localhost:9000" --no-ssl --host-bucket="localhost:9000" ls s3://mybucket

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/homebrew/bin/s3cmd --no-progress --stats --verbose --access_key=***REMOVED*** --secret_key=***REMOVED*** --host=localhost:9000 --no-ssl --host-bucket=localhost:9000 ls s3://mybucket
Problem: <class 'TypeError: sequence item 1: expected str instance, bytes found
S3cmd:   2.3.0
python:   3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)]
environment LANG=NOTSET

Traceback (most recent call last):
  File "/opt/homebrew/bin/s3cmd", line 3286, in <module>
    rc = main()
         ^^^^^^
  File "/opt/homebrew/bin/s3cmd", line 3183, in main
    rc = cmd_func(args)
         ^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/s3cmd", line 167, in cmd_ls
    subcmd_bucket_list(s3, uri, cfg.limit)
  File "/opt/homebrew/bin/s3cmd", line 203, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix, limit = limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/S3/S3.py", line 333, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "/opt/homebrew/lib/python3.12/site-packages/S3/S3.py", line 369, in bucket_list_streaming
    current_list = _get_contents(response["data"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/S3/S3.py", line 351, in _get_contents
    return getListFromXml(data, "Contents")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/S3/BaseUtils.py", line 277, in getListFromXml
    tree = getTreeFromXml(xml)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/S3/BaseUtils.py", line 263, in getTreeFromXml
    xml, xmlns = stripNameSpace(encode_to_s3(xml))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/S3/BaseUtils.py", line 255, in stripNameSpace
    xml = RE_XML_NAMESPACE.sub("\\1\\2", xml, 1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, bytes found

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

`mybucket` is existing and I have access to it, since I created it using `mb` and can do all other operations to it and it's objects.

I am not using any config file, just the params shown in the commands.

**Comment by fviard** [comment]
Thank you for your report, this issue was in fact already fixed in MASTER and there is also a new release available with this correction: 2.4.0.
