### ISSUE TITLE
s3cmd -e put via gpg Problem: <class 'PermissionError: [Errno 13] Permission denied: b''

### ISSUE THREAD

**Issue by col-panic** [s3tools/s3cmd#1368]
Using a command like `s3cmd -e put /root/something.tar.gz s3://some-bucket/ -d` against https://www.exoscale.com/pricing/#block-storage with config file .s3cfg

```
host_base = sos-ch-dk-2.exo.io
host_bucket = %(bucket)s.sos-ch-dk-2.exo.io
access_key = something
secret_key = something
use_https = True
check_ssl_certificate = True
check_ssl_hostname = True
pg_command = /usr/bin/gpg
gpg_passphrase = somepassphrase
```

results in 
```
INFO: Encrypting file /root/something.tar.gz to /tmp/tmpfile-MqDZAWFK8q8d0rFfSoS5...
DEBUG: GPG command:  -c --verbose --no-use-agent --batch --yes --passphrase-fd 0 -o /tmp/tmpfile-MqDZAWFK8q8d0rFfSoS5 /root/mbs.tar.gz
DEBUG: DeUnicodising '' using UTF-8
DEBUG: DeUnicodising '-c' using UTF-8
DEBUG: DeUnicodising '--verbose' using UTF-8
DEBUG: DeUnicodising '--no-use-agent' using UTF-8
DEBUG: DeUnicodising '--batch' using UTF-8
DEBUG: DeUnicodising '--yes' using UTF-8
DEBUG: DeUnicodising '--passphrase-fd' using UTF-8
DEBUG: DeUnicodising '0' using UTF-8
DEBUG: DeUnicodising '-o' using UTF-8
DEBUG: DeUnicodising '/tmp/tmpfile-MqDZAWFK8q8d0rFfSoS5' using UTF-8
DEBUG: DeUnicodising '/root/mbs.tar.gz' using UTF-8

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Invoked as: s3cmd -e put /root/something.tar.gz s3://some-bucket/ -d
Problem: <class 'PermissionError: [Errno 13] Permission denied: b''
S3cmd:   2.1.0
python:   3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 430, in cmd_object_put
    gpg_exitcode, full_name, extra_headers["x-amz-meta-s3tools-gpgenc"] = gpg_encrypt(full_name_orig)
  File "/usr/bin/s3cmd", line 2266, in gpg_encrypt
    code = gpg_command(command, cfg.gpg_passphrase)
  File "/usr/bin/s3cmd", line 2246, in gpg_command
    p = subprocess.Popen(command, stdin = subprocess.PIPE, stdout = subprocess.PIPE, stderr = subprocess.STDOUT,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: b''

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

the file `/tmp/tmpfile-MqDZAWFK8q8d0rFfSoS5` exists, but has 0 size.

**Comment by col-panic** [comment]
Same holds for newest downloaded executable

```
Invoked as: s3cmd-2.4.0/s3cmd -e put something.tar.gz s3://some-bucket/
Problem: <class 'PermissionError: [Errno 13] Permission denied: b''
S3cmd:   2.4.0
python:   3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/root/s3cmd-2.4.0/s3cmd", line 3627, in <module>
    rc = main()
  File "/root/s3cmd-2.4.0/s3cmd", line 3524, in main
    rc = cmd_func(args)
  File "/root/s3cmd-2.4.0/s3cmd", line 460, in cmd_object_put
    gpg_exitcode, full_name, extra_headers["x-amz-meta-s3tools-gpgenc"] = gpg_encrypt(full_name_orig)
  File "/root/s3cmd-2.4.0/s3cmd", line 2730, in gpg_encrypt
    code = gpg_command(command, cfg.gpg_passphrase)
  File "/root/s3cmd-2.4.0/s3cmd", line 2710, in gpg_command
    p = subprocess.Popen(command, stdin = subprocess.PIPE, stdout = subprocess.PIPE, stderr = subprocess.STDOUT,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: b''

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by col-panic** [comment]
Defining these additional parameters seems to work 
```
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
```
