### ISSUE TITLE
KeyError: 'etag' crash - latest

### ISSUE THREAD

**Issue by Jayd603** [s3tools/s3cmd#1406]
This error happens when using s3cmd with latest s3 java libs so it impacts apps.   AWS cli works fine of course

root@da4:~# s3cmd get s3://da4/file.enc /anypath/file.enc

Invoked as: /usr/local/bin/s3cmd get s3://da4/file.enc /anypath/file.enc
Problem: <class 'KeyError: 'etag'
S3cmd:   2.4.0
python:   3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/s3cmd-2.4.0-py3.10.egg/EGG-INFO/scripts/s3cmd", line 3627, in <module>
  File "/usr/local/lib/python3.10/dist-packages/s3cmd-2.4.0-py3.10.egg/EGG-INFO/scripts/s3cmd", line 3524, in main
  File "/usr/local/lib/python3.10/dist-packages/s3cmd-2.4.0-py3.10.egg/EGG-INFO/scripts/s3cmd", line 548, in cmd_object_get
  File "/usr/local/lib/python3.10/dist-packages/s3cmd-2.4.0-py3.10.egg/S3/FileLists.py", line 552, in fetch_remote_list
    _get_remote_attribs(uri, remote_item)
  File "/usr/local/lib/python3.10/dist-packages/s3cmd-2.4.0-py3.10.egg/S3/FileLists.py", line 411, in _get_remote_attribs
    'md5': response['headers']['etag'].strip('"\''),
KeyError: 'etag'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.

**Comment by fviard** [comment]
What is the server that you are using?
Would you mind running the command with the -d flag to see what is happening when it crashes?

**Comment by Jayd603** [comment]
[s3cmd_debug.txt](https://github.com/user-attachments/files/17895332/s3cmd_debug.txt)

**Comment by fviard** [comment]
Thanks for the debug output.
- I see that the server is not respecting the S3 protocol.
- It is listed as "Jetty", it is like a java library but not a S3 server that I would know. Is it a custom home made server that you are using?

It would probably make sense to not necessarily requires to have "etag" just for a GET, as we will not compare the MD5, but without "etag" the server will not be that good for any other operation, so i'm not sure that such a special edge case worth the change. Except if you have more info.
