### ISSUE TITLE
"s3cmd ls": ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by yarikoptic** [s3tools/s3cmd#172]
First I ran into https://github.com/s3tools/s3cmd/pull/162 and then found git://github.com/mdomsch/s3cmd.git clone with merges, so trying that one now (Python 2.7.4 in Debian)

```
$> git describe                                                
v1.5.0-alpha3-49-gd8807df

$> PATH=$PWD:$PATH ./s3cmd info s3://yoh-test-bucket/index.html

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: ./s3cmd info s3://yoh-test-bucket/index.htmlProblem: ParseError: no element found: line 1, column 0
S3cmd:   1.5.0-alpha3

Traceback (most recent call last):
  File "./s3cmd", line 2187, in <module>
    main()
  File "./s3cmd", line 2112, in main
    cmd_func(args)
  File "./s3cmd", line 618, in cmd_info
    info = s3.object_info(uri)
  File "/home/yoh/proj/misc/s3cmd/S3/S3.py", line 491, in object_info
    response = self.send_request(request)
  File "/home/yoh/proj/misc/s3cmd/S3/S3.py", line 690, in send_request
    redir_bucket = getTextFromXml(response['data'], ".//Bucket")
  File "/home/yoh/proj/misc/s3cmd/S3/Utils.py", line 111, in getTextFromXml
    tree = getTreeFromXml(xml)
  File "/home/yoh/proj/misc/s3cmd/S3/Utils.py", line 78, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by fviard** [comment]
Closing old ticket.
Issue probably already resolved in last versions.

**Comment by yarikoptic** [comment]
oh, sorry -- I have missed the comment that permissions were wrong... confirming that on debian with 2.0.1 it works without the elderly reported crash
