### ISSUE TITLE
Same filename error

### ISSUE THREAD

**Issue by wyred** [s3tools/s3cmd#330]
I'm trying to make a backup of my s3 bucket to a local machine. The s3 bucket contains about 50000+ image files.

Invoked as: /Users/username/s3cmd-1.5.0-beta1/s3cmd sync -v --skip-existing s3://redacted/resized/ resized/Problem: Error: `resized/A92WnxocWFjB5ZhiL8laN4bcyekYpeJQTX53JQnA_bg.png` and `resized/A92WnxocWFjB5ZhiL8laN4bcyekYpeJQTX53JQnA_bg.png` are the same file
S3cmd:   1.5.0-beta1

Traceback (most recent call last):
  File "/Users/username/s3cmd-1.5.0-beta1/s3cmd", line 2276, in <module>
    main()
  File "/Users/username/s3cmd-1.5.0-beta1/s3cmd", line 2201, in main
    cmd_func(args)
  File "/Users/username/s3cmd-1.5.0-beta1/s3cmd", line 1290, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/Users/username/s3cmd-1.5.0-beta1/s3cmd", line 971, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/Users/username/s3cmd-1.5.0-beta1/s3cmd", line 1003, in local_copy
    shutil.copy2(src_file, dst_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `resized/A92WnxocWFjB5ZhiL8laN4bcyekYpeJQTX53JQnA_bg.png` and `resized/A92WnxocWFjB5ZhiL8laN4bcyekYpeJQTX53JQnA_bg.png` are the same file

**Comment by fviard** [comment]
Fyi, normally it is better handled now, but it is probably that you had a "file" and 'folder' with the same name inside your cloud. Like:
- s3://bucket/myfolder/myfile.txt
- s3://bucket/myfolder   <- regular file despite the name.
So s3cmd is confused!
