### ISSUE TITLE
cfinfo chokes on CloudFront custom origin URLs

### ISSUE THREAD

**Issue by mietek** [s3tools/s3cmd#379]
Take a look at Amazon's [“Speed Up Your Website Using CloudFront”](http://docs.aws.amazon.com/gettingstarted/latest/swh/getting-started-create-cfdist.html):

> In the _Origin Domain Name_ box, enter the Amazon S3 static website hosting endpoint for your bucket. This is the value that you copied in Step 4 of the procedure “To configure your root domain Amazon S3 bucket as a website”, for example, _example.com.s3-website-us-east-1.amazonaws.com._

`s3cmd cfinfo` fails when confronted with a CloudFront distribution using a custom origin domain name:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: ValueError: Unable to parse URL: omitted.s3-website-eu-west-1.amazonaws.com
S3cmd:   1.0.1

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2006, in <module>
    main()
  File "/usr/local/bin/s3cmd", line 1950, in main
    cmd_func(args)
  File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/CloudFront.py", line 460, in info
    pretty_output("Origin", S3UriS3.httpurl_to_s3uri(dc.info['Origin']))
  File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3Uri.py", line 112, in httpurl_to_s3uri
    raise ValueError("Unable to parse URL: %s" % http_url)
ValueError: Unable to parse URL: omitted.s3-website-eu-west-1.amazonaws.com

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by pbrisbin** [comment]
FWIW: this seems to be fixed

```
% s3cmd --version
s3cmd version 1.5.0-rc1
% s3cmd cfinfo
Origin:         http://pbrisbin.com.s3-website-us-east-1.amazonaws.com/
DistId:         cf://E1X0T38U6FY9ST
DomainName:     d2iuddmshbwj1q.cloudfront.net
CNAMEs:         pbrisbin.com
Status:         Deployed
Enabled:        True
```

**Comment by mietek** [comment]
This issue is no longer relevant.
