### ISSUE TITLE
signature v4 -> RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by fviard** [s3tools/s3cmd#444]
Code to get location for signature v4, go in an infinite recursion when the server don't support the "get location" request and return a "400" error.

Relevant bits of the log output:
DEBUG: format_uri(): /s3test/?location
...
DEBUG: Response: {'status': 400, 'headers': {'content-length': '142', 'server': 'Tengine/2.0.3', 'connection': 'keep-alive', 'x-trans-id': 'tx1125c549f32e4c68a1d89-005490659c', 'date': 'Tue, 16 Dec 2014 17:02:20 GMT', 'content-type': 'text/xml; charset=UTF-8'}, 'reason': 'Bad Request', 'data': '<?xml version="1.0" encoding="UTF-8"?>\r\n<Error>\r\n  <Code>InvalidURI</Code>\r\n  <Message>Could not parse the specified URI</Message>\r\n</Error>\r\n'}
...
Invoked as: ./s3cmd -v -d -c s3cfg_flo sync testdir/ s3://s3test/testooo501/
Problem: RuntimeError: maximum recursion depth exceeded
S3cmd:   1.5.0-rc1
python:   2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
environment LANG=fr_FR.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 2532, in <module>
    rc = main()
  File "./s3cmd", line 2450, in main
    rc = cmd_func(args)
  File "./s3cmd", line 1470, in cmd_sync
    return cmd_sync_local2remote(args)
  File "./s3cmd", line 1447, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "./s3cmd", line 1252, in _single_process
    rc = _child(destination_base, local_list)
  File "./s3cmd", line 1328, in _child
    remote_list, dst_exclude_list = fetch_remote_list(destination_base, recursive = True, require_attribs = True)
  File "/S3/FileLists.py", line 417, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/S3/FileLists.py", line 357, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "/S3/S3.py", line 277, in bucket_list
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
  File "/S3/S3.py", line 301, in bucket_list_noparse
    response = self.send_request(request)
  File "/S3/S3.py", line 962, in send_request
    region = self.get_bucket_location(s3_uri)
  File "/S3/S3.py", line 335, in get_bucket_location
    response = self.send_request(request)
  File "/S3/S3.py", line 962, in send_request
    region = self.get_bucket_location(s3_uri)
  File "/S3/S3.py", line 335, in get_bucket_location
...thousands of lines...
  File "/S3/S3.py", line 962, in send_request
    region = self.get_bucket_location(s3_uri)
  File "/S3/S3.py", line 335, in get_bucket_location
    response = self.send_request(request)
  File "/S3/S3.py", line 962, in send_request
    region = self.get_bucket_location(s3_uri)
  File "/S3/S3.py", line 334, in get_bucket_location
    request = self.create_request("BUCKET_LIST", bucket = uri.bucket(), extra = "?location")
  File "/S3/S3.py", line 915, in create_request
    request = S3Request(self, method_string, resource, headers, body, params)
  File "/S3/S3.py", line 122, in __init__
    self.sign()
  File "/S3/S3.py", line 166, in sign
    self.s3.get_hostname(self.resource['bucket']),
  File "/S3/S3.py", line 235, in get_hostname
    debug('get_hostname(%s): %s' % (bucket, host))
  File "/usr/lib/python2.7/logging/__init__.py", line 1622, in debug
    root.debug(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 67, in print_tb
    '  File "%s", line %d, in %s' % (filename, lineno, name))
  File "/usr/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
RuntimeError: maximum recursion depth exceeded

The point is that "send_request" try call "get_bucket_location" when encountering a 400 error. But "get_bucket_location" call itself "send_request" to perform its task and if that request result in a "400" error, then get_bucket_location will be called recursively ...again and again...
In send_request:
"
if response["status"] == 400:
            if 'data' in response and len(response['data']) > 0 and getTextFromXml(response['data'], 'Code') == 'AuthorizationHeaderMalformed':
                region = getTextFromXml(response['data'], 'Region')
            else:
                s3_uri = S3Uri('s3://' + request.resource['bucket'])
                region = self.get_bucket_location(s3_uri)
"

**Comment by mdomsch** [comment]
Fixed in ad94cbb4 by getting the suggested location out of the error response without having to issue a get_bucket_location() call, which will fail.  This is fixed on master branch.
