### ISSUE TITLE
Problem: error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by andreas-venturini** [s3tools/s3cmd#509]
Using latest code from git master branch (as of Mar 23rd, 2015)

```bash
Invoked as: /usr/local/bin/s3cmd sync --delete-removed --debug --exclude-from /export/home/backup_dir/files.exclude s3://bucket/ /iscsi_s3backup/bucket-backup/
Problem: error: [Errno 32] Broken pipe
S3cmd:   1.5.2
python:   2.7.8 (default, Feb 12 2015, 17:07:28) 
[GCC 4.5.2]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2563, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2475, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1491, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/local/bin/s3cmd", line 960, in cmd_sync_remote2local
    remote_list, src_exclude_list = fetch_remote_list(args[:-1], recursive = True, require_attribs = True)
  File "/export/home/andreas/s3cmd-master/S3/FileLists.py", line 444, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/export/home/andreas/s3cmd-master/S3/FileLists.py", line 419, in _get_filelist_remote
    _get_remote_attribs(S3Uri(object_uri_str), rem_list[key])
  File "/export/home/andreas/s3cmd-master/S3/FileLists.py", line 347, in _get_remote_attribs
    response = S3(cfg).object_info(uri)
  File "/export/home/andreas/s3cmd-master/S3/S3.py", line 751, in object_info
    response = self.send_request(request)
  File "/export/home/andreas/s3cmd-master/S3/S3.py", line 975, in send_request
    conn.c.request(method_string, uri, request.body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 820, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/ssl.py", line 234, in sendall
    v = self.send(data[count:])
  File "/usr/local/lib/python2.7/ssl.py", line 203, in send
    v = self._sslobj.write(data)
error: [Errno 32] Broken pipe

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by mdomsch** [comment]
Seeing this from several reports this week.  github.com/mdomsch/s3cmd has a
bug/epipe2 branch but it doesn't fix all the cases that are tripping.
Needs more work.

On Tue, Mar 24, 2015 at 8:15 AM, Andreas Venturini <notifications@github.com

**Comment by mdomsch** [comment]
I pushed out another attempt to fix these into the github.com/mdomsch/s3cmd
bug/epipe-2 branch.  Please give that a try.

**Comment by andreas-venturini** [comment]
I pulled the branch and there were no more broken pipe errors. However, other errors like this (https://github.com/s3tools/s3cmd/issues/330) popped up out of nowhere (never seen those before). Is it possible to get this merged into the current master branch?

**Comment by mdomsch** [comment]
This is merged to master now, thanks.

**Comment by fviard** [comment]
This issue should now be fixed in master.
Please give it a try.
