### ISSUE TITLE
KeyError: 'date'

### ISSUE THREAD

**Issue by alex-LE** [s3tools/s3cmd#542]
Hi, i currently have some issues running my backup script. I use s3cmd sync to upload my backups to dreamobjects (dreamhost.com). But its not working any more.
I get the following error:
```
Problem: KeyError: 'date'
S3cmd:   1.5.2
python:   2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2]
environment LANG=None

Traceback (most recent call last):
  File "/root/bin/s3cmd", line 2548, in <module>
    rc = main()
  File "/root/bin/s3cmd", line 2460, in main
    rc = cmd_func(args)
  File "/root/bin/s3cmd", line 1479, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/root/bin/s3cmd", line 1456, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "/root/bin/s3cmd", line 1261, in _single_process
    rc = _child(destination_base, local_list)
  File "/root/bin/s3cmd", line 1337, in _child
    remote_list, dst_exclude_list = fetch_remote_list(destination_base, recursive = True, require_attribs = True)
  File "/root/bin/S3/FileLists.py", line 419, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/root/bin/S3/FileLists.py", line 394, in _get_filelist_remote
    _get_remote_attribs(S3Uri(object_uri_str), rem_list[key])
  File "/root/bin/S3/FileLists.py", line 329, in _get_remote_attribs
    'timestamp' : dateRFC822toUnix(response['headers']['date'])
KeyError: 'date'
```
when running this command:
```
/root/bin/s3cmd sync /var/backup/ s3://mybackupbucket/dir/
```
I've also tried the lastest master version from github with the same result.
Its working with AWS by the way.
But i really need Dreamobjects.
Any ideas?

Alex

**Comment by alex-LE** [comment]
The traceback for the lastest version:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2586, in <module>
    rc = main()
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2498, in main
    rc = cmd_func(args)
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1496, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1473, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1278, in _single_process
    rc = _child(destination_base, local_list)
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1354, in _child
    remote_list, dst_exclude_list = fetch_remote_list(destination_base, recursive = True, require_attribs = True)
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/S3/FileLists.py", line 444, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/S3/FileLists.py", line 419, in _get_filelist_remote
    _get_remote_attribs(S3Uri(object_uri_str), rem_list[key])
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.5.2-py2.7.egg/S3/FileLists.py", line 354, in _get_remote_attribs
    'timestamp' : dateRFC822toUnix(response['headers']['date'])
KeyError: 'date'
```

**Comment by mdomsch** [comment]
Does it sync some files, but not quite all?  I've tested against
DreamObjects before and it's been mostly fine (some features aren't
implemented of course).  I just ran a sync into DreamObjects now with
upstream master and it worked fine.  Is this an occasional failure, for
only one file, or always?

Thanks,
Matt

**Comment by scyclops** [comment]
I've been running into this error for the past few days with DreamObjects as well.  It appears to occur before any new files are uploaded.  I just modified S3/FileLists.py:329 to change:

> response['headers']['date']

to:

> response['headers'].get('date') or response['headers']['last-modified']

and this appears to have made it run and sync (though I'm curious to know if this change is technically valid and whether or not it will cause problems).

I made this change because 'last-modified' was the only key in response['headers'] that had date information in it (the only other keys present were 'content-length', 'accept-ranges', 'x-amz-meta-s3cmd-attrs', 'etag', and 'content-type').

**Comment by mdomsch** [comment]
it should certainly be last-modified, and not date.  date is the server's
current time, which is meaningless to us.  I wonder how long that's been in
there.  Thanks for catching it.

**Comment by mdomsch** [comment]
fixed on upstream master branch now, with credit to you.  Thanks!

**Comment by alex-LE** [comment]
I've made the update to the master version, but now i get a 404 error after s3cmd has processed the local files:

```
INFO: Retrieving list of remote files for s3://nas_backup/ ...
ERROR: S3 error: 404 (Not Found):
```

"s3cmd ls" works and i can browse my bucket.

**Comment by alex-LE** [comment]
Found the problem, the bucket name contained a underscore.
