### ISSUE TITLE
Configure totally failing without a target bucket

### ISSUE THREAD

**Issue by rrshaban** [s3tools/s3cmd#552]
```
$ s3cmd

ERROR: /Users/razi/.s3cfg: None

ERROR: Configuration file not available.

ERROR: Consider using --configure parameter to create one.


$ s3cmd --configure


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    An unexpected error has occurred.

  Please try reproducing the error using

  the latest s3cmd code from the git master

  branch found at:

    https://github.com/s3tools/s3cmd

  If the error persists, please report the

  following lines (removing any private

  info as necessary) to:

   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Invoked as: /usr/local/Cellar/s3cmd/1.5.2/libexec/bin/s3cmd --configure

Problem: BadStatusLine: ''

S3cmd:   1.5.2

python:   2.7.5 (default, Mar  9 2014, 22:15:05)

[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]

environment LANG=en_US.UTF-8


Traceback (most recent call last):

  File "/usr/local/Cellar/s3cmd/1.5.2/libexec/bin/s3cmd", line 2548, in <module>

    rc = main()

  File "/usr/local/Cellar/s3cmd/1.5.2/libexec/bin/s3cmd", line 2279, in main

    cfg = Config(options.config, options.access_key, options.secret_key)

  File "/usr/local/Cellar/s3cmd/1.5.2/libexec/lib/python2.7/site-packages/S3/Config.py", line 148, in __init__

    self.role_config()

  File "/usr/local/Cellar/s3cmd/1.5.2/libexec/lib/python2.7/site-packages/S3/Config.py", line 160, in role_config

    resp = conn.getresponse()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse

    response.begin()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin

    version, status, reason = self._read_status()

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status

    raise BadStatusLine(line)

BadStatusLine: ''


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    An unexpected error has occurred.

  Please try reproducing the error using

  the latest s3cmd code from the git master

  branch found at:

    https://github.com/s3tools/s3cmd

  If the error persists, please report the

  above lines (removing any private

  info as necessary) to:

   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

BUT, when I try running 

```
$ sudo s3cmd --configure
Password:

Enter new values or accept defaults in brackets with Enter.
Refer to user manual for detailed description of all options.
```

It works! Itwalks me through the whole new settings process. Except, at the end:

```
Test access with supplied credentials? [Y/n] Y
Please wait, attempting to list all buckets...
ERROR: S3 error: Access Denied
```

That's weird. Let's try connecting to my s3 bucket:

```
$ s3cmd ls s3://[BUCKET]/
ERROR: /Users/razi/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
```

**Comment by rrshaban** [comment]
Now, if I try configuring to a specific bucket:

```
$ s3cmd --configure s3://[BUCKET]

...

Test access with supplied credentials? [Y/n] Y
Please wait, attempting to list bucket: s3://[BUCKET]
Success. Your access key and secret key worked fine :-)
```

That works fine. The [documentation](http://s3tools.org/usage) says
```
--configure           Invoke interactive (re)configuration tool. Optionally
                        use as '--configure s3://some-bucket' to test access
                        to a specific bucket instead of attempting to list
                        them all.
```

But it seems that it isn't really optional at all -- is this a bug or an issue with the documentation?

**Comment by mdomsch** [comment]
It must be a bug.  The code in run_configure() clearly looks to not do a
List All Buckets if a bucket is specified.

**Comment by fviard** [comment]
Not reproducible in master version.
