### ISSUE TITLE
NameError: global name 'EX_SOMEFAILED' is not defined

### ISSUE THREAD

**Issue by ezbik** [s3tools/s3cmd#576]
s3cmd version: 1393df1e9ea3fc543814f387ab94bc2855eca4a6
Sometimes it fails with strange error, see below.

```
/var/dxm.backups/20150623.06.tgz.lst -> s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst  [1 of 1]
  131072 of 2675485     4% in    0s   176.43 kB/s  failed
WARNING: Upload failed: /protest01.wsynth.net/20150623.06.tgz.lst ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
/var/dxm.backups/20150623.06.tgz.lst -> s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst  [1 of 1]
  262144 of 2675485     9% in    1s   166.54 kB/s  failed
WARNING: Upload failed: /protest01.wsynth.net/20150623.06.tgz.lst ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.01)
WARNING: Waiting 6 sec...
/var/dxm.backups/20150623.06.tgz.lst -> s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst  [1 of 1]
  196608 of 2675485     7% in    1s   121.04 kB/s  failed
WARNING: Upload failed: /protest01.wsynth.net/20150623.06.tgz.lst ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.05)
WARNING: Waiting 9 sec...
/var/dxm.backups/20150623.06.tgz.lst -> s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst  [1 of 1]
  720896 of 2675485    26% in    1s   379.91 kB/s  failed
WARNING: Upload failed: /protest01.wsynth.net/20150623.06.tgz.lst ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.25)
WARNING: Waiting 12 sec...
/var/dxm.backups/20150623.06.tgz.lst -> s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst  [1 of 1]
  131072 of 2675485     4% in    0s   172.91 kB/s  failed
WARNING: Upload failed: /protest01.wsynth.net/20150623.06.tgz.lst ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=1.25)
WARNING: Waiting 15 sec...
/var/dxm.backups/20150623.06.tgz.lst -> s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst  [1 of 1]
  131072 of 2675485     4% in    1s    97.91 kB/s  failed
ERROR: Upload of '/var/dxm.backups/20150623.06.tgz.lst' failed too many times. Skipping that file.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/s3cmd/s3cmd --no-encrypt --delete-removed --multipart-chunk-size-mb=100 --no-preserve --no-check-md5 --progress put /var/dxm.backups/20150623.06.tgz.lst s3://synthdxmbackup/protest01.wsynth.net/20150623.06.tgz.lst
Problem: NameError: global name 'EX_SOMEFAILED' is not defined
S3cmd:   1.5.2
python:   2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/opt/s3cmd/s3cmd", line 2595, in <module>
    rc = main()
  File "/opt/s3cmd/s3cmd", line 2503, in main
    rc = cmd_func(args)
  File "/opt/s3cmd/s3cmd", line 394, in cmd_object_put
    ret = EX_SOMEFAILED
NameError: global name 'EX_SOMEFAILED' is not defined

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by fviard** [comment]
Hi,
thank you for your report, indeed there is a bug in the error reporting.
For some reason, you have a file that doesn't want to be transfered. So, after a certain number of failures, the system want to skip it and continue but by preserving the information that backup is partial.
But there there is a typo.
I will fix that.

**Comment by fviard** [comment]
Should be fixed.
Thank you again for the report!
