### ISSUE TITLE
s3cmd not completing job. UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 96: ordinal not in range(128)

### ISSUE THREAD

**Issue by unclewalter** [s3tools/s3cmd#637]
I'm having and issue with s3cmd where it is not completing a sync job. This is what's coming up. I get this both with version 1.5.2 and 1.6.0.

```
Invoked as: ./s3cmd sync s3://tilde-fixed-media/uploads/ --skip-existing /Users/kevanatkins/Google Drive/Fixed Media Submissions/
Traceback (most recent call last):
  File "./s3cmd", line 2876, in <module>
    report_exception(e)
  File "./s3cmd", line 2745, in report_exception
    sys.stderr.write(u"Problem: %s: %s\n" % (e_class, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 96: ordinal not in range(128)
```

Then if I run the command again with the local folder partially populated (since it cannot complete the job) up to this point, I get this:

```
Invoked as: ./s3cmd sync s3://tilde-fixed-media/uploads/ --skip-existing /Users/kevanatkins/Google Drive/Fixed Media Submissions/
Problem: Error: `/Users/kevanatkins/Google Drive/Fixed Media Submissions/vin@vgiles.net_Vincent-Giles/05 Smash I.mp3` and `/Users/kevanatkins/Google Drive/Fixed Media Submissions/vin@vgiles.net_vincent-giles/05 Smash I.mp3` are the same file
S3cmd:   1.6.0
python:   2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
environment LANG=en_AU.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 2805, in <module>
    rc = main()
  File "./s3cmd", line 2713, in main
    rc = cmd_func(args)
  File "./s3cmd", line 1668, in cmd_sync
    return cmd_sync_remote2local(args)
  File "./s3cmd", line 1315, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "./s3cmd", line 1349, in local_copy
    shutil.copy2(deunicodise(src_file), deunicodise(dst_file))
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/Users/kevanatkins/Google Drive/Fixed Media Submissions/vin@vgiles.net_Vincent-Giles/05 Smash I.mp3` and `/Users/kevanatkins/Google Drive/Fixed Media Submissions/vin@vgiles.net_vincent-giles/05 Smash I.mp3` are the same file
```

What's odd is that it's treating folder names with different cases as equivalent and attempting to merge them in the second error.

**Comment by mdomsch** [comment]
You have a case-insensitive file system.  The directories have identical
names if you ignore case. That isn't a mode I had tried before...  Ugh.

**Comment by unclewalter** [comment]
Alright. I'll modify my app to force lowercase for now. Thanks.
