### ISSUE TITLE
s3cmd erroring on get

### ISSUE THREAD

**Issue by noilly** [s3tools/s3cmd#679]
```    
virtualbox-iso: Problem: UnboundLocalError: local variable 'conn' re
 before assignment
virtualbox-iso: S3cmd:   1.6.0
virtualbox-iso: python:   2.7.5 (default, Nov 20 2015, 02:00:19)
virtualbox-iso: [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
virtualbox-iso: environment LANG=en_AU.UTF-8
virtualbox-iso:
virtualbox-iso: Traceback (most recent call last):
virtualbox-iso: File "/usr/bin/s3cmd", line 2805, in <module>
virtualbox-iso: rc = main()
virtualbox-iso: File "/usr/bin/s3cmd", line 2713, in main
virtualbox-iso: rc = cmd_func(args)
virtualbox-iso: File "/usr/bin/s3cmd", line 549, in cmd_object_get
virtualbox-iso: response = s3.object_get(uri, dst_stream, destinatio
_position = start_position, extra_label = seq_label)
virtualbox-iso: File "/usr/lib/python2.7/site-packages/S3/S3.py", li
in object_get
virtualbox-iso: response = self.recv_file(request, stream, labels, s
ition)
virtualbox-iso: File "/usr/lib/python2.7/site-packages/S3/S3.py", li
 in recv_file
virtualbox-iso: conn.counter = ConnMan.conn_max_counter
virtualbox-iso: UnboundLocalError: local variable 'conn' referenced before assignment
```

**Comment by mdomsch** [comment]
Fixed on upstream master branch.

**Comment by fviard** [comment]
@noilly Can you confirm that it is fixed for your? so we can close the issue? thanks!

**Comment by noilly** [comment]
Sorry, I didn't get notified of an update! Will do as soon as I can. :)
