### ISSUE TITLE
Problem: Error: `*.jpg` and `*.jpg` are the same file

### ISSUE THREAD

**Issue by andreas-venturini** [s3tools/s3cmd#686]
I haven't tested with the latest master but I will do so once I can confirm that the below issue is reproducible. 

```
Problem: Error: `/iscsi_s3backup/production/2bb36f83-a2de-4d3e-bb9e-dcdc1e7ff0ce.jpg` and `/iscsi_s3backup/production/2bb36f83-a2de-4d3e-bb9e-dcdc1e7ff0ce.jpg` are the same file
S3cmd:   1.5.0-alpha3

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2094, in <module>
    main()
  File "/usr/local/bin/s3cmd", line 2034, in main
    cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1193, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/local/bin/s3cmd", line 894, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/usr/local/bin/s3cmd", line 926, in local_copy
    shutil.copy2(src_file, dst_file)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/iscsi_s3backup/production/2bb36f83-a2de-4d3e-bb9e-dcdc1e7ff0ce.jpg` and `/iscsi_s3backup/production/2bb36f83-a2de-4d3e-bb9e-dcdc1e7ff0ce.jpg` are the same file
```

**Comment by fviard** [comment]
@andreas-venturini 
Can you try with master? i think that any issue with that would be fixed already.
Otherwise, can you post the command line that you use and tell me if you are using "windows", "linux", "mac" or maybe a case insensititve file system?

**Comment by andreas-venturini** [comment]
I have switched to the aws client a couple months ago - I am afraid I can no longer be of any help and don't have the command line that I used back then anymore. I suggest to close this issue.
