### ISSUE TITLE
ERROR: S3 error: 404 (Not Found)

### ISSUE THREAD

**Issue by amitsidhim** [s3tools/s3cmd#713]
Hello Team, 

I am trying to configure s3cmd , that lists the bucket on the destination host. This host is kind of emulation  to Amazon using s3 protocol . Following the are the debug Errors ::

```

```
> DEBUG: non-proxied HTTPConnection(s3.dellpe_01)
> DEBUG: format_uri(): /
> DEBUG: Sending request method_string='GET', uri='/', headers={'Authorization': 'AWS FWJVCDUPUBYHSCORCCTT:LrvhvY1ZegtO5PNFARUjViMoQ1o=', 'x-amz-date': 'Sun, 06 Mar 2016 07:24:00 +0000'}, body=(0 bytes)
> DEBUG: Response: {'status': 404, 'headers': {'content-length': '0'}, 'reason': 'Not Found', 'data': ''}
> DEBUG: ConnMan.put(): connection put back to pool (http://s3.dellpe_01#1)
> DEBUG: S3Error: 404 (Not Found)
> DEBUG: HttpHeader: content-length: 0
> ERROR: S3 error: 404 (Not Found)
```

```

s3 Version :: 

[root@vx s3cmd]# ./s3cmd --version
s3cmd version 1.6.1
[root@vx s3cmd]#

**Comment by fviard** [comment]
It looks like that your configuration is wrong.
Can you show us your s3cfg file?
(maybe not forgetting scramble the access_key and secret_key entries)

**Comment by amitsidhim** [comment]
Hello Thanks For Your Reponse 

Here is the situation in brief. 


Scenario ::


I am trying to use s3cmd for testing s3 kind of storage , that is running locally on network, that emulates the behaviour of Amazon. So , all the request goes to  a designated IP address . e.g. : <192.168.1.1:8314>  or  http://s3.sever.com:8143 . To facilitate this I made  following changes on s3 configuraiton file . Now, the s2ls command works but any other operation fails. This setup work perfectly fine with s3 browser. The list commands works too. 

Outputs of 

```
Lisitng Buckets 

root@8500 s3cmd]# ./s3cmd ls
1970-01-01 05:30  s3://Test1
1970-01-01 05:30  s3://bucket1
[root@8500 s3cmd]#

```
``



```
creating Buckets :: 

[root@vxctf8500 s3cmd]# ./s3cmd mb s3://bucket104 -d
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/root/.s3cfg'
DEBUG: ConfigParser: access_key->Nj...17_chars...y
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->no
DEBUG: ConfigParser: ca_certs_file->
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->True
DEBUG: ConfigParser: check_ssl_hostname->True
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3.n8500_01:8143
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.n8500_01
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: multipart_max_chunks->10000
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: secret_key->MT...37_chars...5
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: signature_v2->False
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stats->False
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->False
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://s3.n8500_01:8143
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'mb' using UTF-8
DEBUG: Unicodising 's3://bucket104' using UTF-8
DEBUG: Command: mb
DEBUG: bucket_location: <CreateBucketConfiguration><LocationConstraint>no</LocationConstraint></CreateBucketConfiguration>
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v4
DEBUG: get_hostname(bucket104): bucket104.s3.n8500_01
DEBUG: canonical_headers = host:bucket104.s3.n8500_01
x-amz-content-sha256:bc809ce779e06c392fb73db9d172fb1f39dd4a5116bd13ef2095e79e51a667b3
x-amz-date:20160315T203725Z

DEBUG: Canonical Request:
PUT
/

host:bucket104.s3.n8500_01
x-amz-content-sha256:bc809ce779e06c392fb73db9d172fb1f39dd4a5116bd13ef2095e79e51a667b3
x-amz-date:20160315T203725Z

host;x-amz-content-sha256;x-amz-date
bc809ce779e06c392fb73db9d172fb1f39dd4a5116bd13ef2095e79e51a667b3
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'bc809ce779e06c392fb73db9d172fb1f39dd4a5116bd13ef2095e79e51a667b3', 'Authorization': 'AWS4-HMAC-SHA256 Credential=NjI3NzQzMjM1NjAxZTQy/20160315/no/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=3496a3e2954c98587a514b631407c7ac8f690aaa8ff538983ca1f0ca786937c3', 'x-amz-date': '20160315T203725Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(bucket104): bucket104.s3.n8500_01
DEBUG: ConnMan.get(): creating new connection: http://bucket104.s3.n8500_01
DEBUG: non-proxied HTTPConnection(bucket104.s3.n8500_01)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising './s3cmd' using UTF-8
DEBUG: Unicodising 'mb' using UTF-8
DEBUG: Unicodising 's3://bucket104' using UTF-8
DEBUG: Unicodising '-d' using UTF-8
Invoked as: ./s3cmd mb s3://bucket104 -d
Problem: gaierror: [Errno -2] Name or service not known
S3cmd:   1.6.1
python:   2.6.6 (r266:84292, May 22 2015, 08:34:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 2919, in <module>
    rc = main()
  File "./s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "./s3cmd", line 205, in cmd_bucket_create
    response = s3.bucket_create(uri.bucket(), cfg.bucket_location)
  File "/s3cmd/S3/S3.py", line 367, in bucket_create
    response = self.send_request(request)
  File "/s3cmd/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/s3cmd/S3/ConnMan.py", line 192, in get
    conn.c.connect()
  File "/usr/lib64/python2.6/httplib.py", line 742, in connect
    self.timeout)
  File "/usr/lib64/python2.6/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```


S3 Configuration File :: 


```
[default]
access_key = xxxxxxxxxx
access_token =
add_encoding_exts =
add_headers =
bucket_location = no
ca_certs_file =
cache_file =
check_ssl_certificate = True
check_ssl_hostname = True
cloudfront_host = cloudfront.amazonaws.com
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
expiry_date =
expiry_days =
expiry_prefix =
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase =
guess_mime_type = True
host_base = s3.n8500_01:8143
host_bucket = %(bucket)s.s3.n8500_01
human_readable_sizes = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
kms_key =
limitrate = 0
list_md5 = False
log_target_prefix =
long_listing = False
max_delete = -1
mime_type =
multipart_chunk_size_mb = 15
multipart_max_chunks = 10000
preserve_attrs = True
progress_meter = True
#proxy_host = 10.209.194.22
#proxy_port = 8143
put_continue = False
recursive = False
recv_chunk = 65536
reduced_redundancy = False
requester_pays = False
restore_days = 1
secret_key = xxxxxxxxxx
send_chunk = 65536
server_side_encryption = False
signature_v2 = False
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
stats = False
stop_on_error = False
storage_class =
urlencoding_mode = normal
use_https = False
use_mime_magic = True
verbosity = WARNING
#website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_endpoint = http://s3.n8500_01:8143
website_error =
website_index = index.html

```

**Comment by amitsidhim** [comment]
Besides If I have the host names in the configuration Files to some .com e.g s3.n8500.com it give the following error 

ERROR: S3 error: 404 (Not Found)

**Comment by fviard** [comment]
Ok, so I see 2 things in your configuration:
host_base = s3.n8500_01:8143
host_bucket = %(bucket)s.s3.n8500_01

Don't you have forget the custom port info for host bucket?
Like host_bucket = %(bucket)s.s3.n8500_01:8143

But if that still not work, that means that your server doesn't support "dns" based hostname but only "path" based hostname. Ie it is possible to access:
http://s3.n8500_01:8143/bucket104/somefile.txt
But not:
http://bucket104.s3.n8500_01:8143/somefile.txt

To fit such a setup, remove "%(bucket)s" meta of the host_bucket config.
Example:
host_bucket = s3.n8500_01:8143
or
host_bucket = s3.n8500_01

**Comment by amitsidhim** [comment]
Thanks a lot for your support ,  the tool has started working now.
