### ISSUE TITLE
ParseError: syntax error: line 1, column 54

### ISSUE THREAD

**Issue by lzw06061139** [s3tools/s3cmd#730]
I used s3cmd tool to test ceph radosgw, and have configured s3cmd with `s3cmd –configure` beforehand,
While I launched `s3cmd ls` to list buckets with root privilege, I got an error as following:
```
Invoked as: /usr/bin/s3cmd ls
Problem: ParseError: syntax error: line 1, column 54
S3cmd:   1.6.1
python:   2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 291, in list_all_buckets
    response["list"] = getListFromXml(response["data"], "Bucket")
  File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 101, in getListFromXml
    tree = getTreeFromXml(xml)
  File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 89, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 54
```
I've already gone over page : https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions, found the 4th issue(Problem: ParseError: syntax error: line 1, column 0) on the page is similar, it only happened on version prior to v1.5.2 and my installed s3cmd tool is the lastest.

I launched `ls` command with debug mode again  `s3cmd –debug ls`, and I got outputs as follows: 

```
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/root/.s3cfg'
DEBUG: ConfigParser: access_key->X6...17_chars...G
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->default
DEBUG: ConfigParser: ca_certs_file->
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->True
DEBUG: ConfigParser: check_ssl_hostname->True
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->12...3_chars...6
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->ceph-101-181
DEBUG: ConfigParser: host_bucket->%(bucket)s.ceph-101-181
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: multipart_max_chunks->10000
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: secret_key->l7...37_chars...4
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: signature_v2->False
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stats->False
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config cache_file -> 
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'ls' using UTF-8
DEBUG: Command: ls
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Thu, 21 Apr 2016 12:22:08 +0000\n/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(None): ceph-101-181
DEBUG: ConnMan.get(): creating new connection: https://ceph-101-181
DEBUG: Using ca_certs_file None
DEBUG: httplib.HTTPSConnection() has neither context nor check_hostname
DEBUG: non-proxied HTTPSConnection(ceph-101-181)
DEBUG: format_uri(): /
DEBUG: Sending request method_string='GET', uri='/', headers={'Authorization': 'AWS X6NZ28M7LR94BFEAB9EG:9lnyr4N1NTi+2kplxYnCfNhDhjw=', 'x-amz-date': 'Thu, 21 Apr 2016 12:22:08 +0000'}, body=(0 bytes)
DEBUG: Response: {'status': 200, 'headers': {'date': 'Thu, 21 Apr 2016 12:22:08 GMT', 'content-length': '903', 'content-type': 'text/html;charset=ISO-8859-1', 'server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips'}, 'reason': 'OK', 'data': '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<html>\n <head>\n  <title>Index of /</title>\n </head>\n <body>\n<h1>Index of /</h1>\n  <table>\n   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>\n   <tr><th colspan="5"><hr></th></tr>\n<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="keys/">keys/</a>                  </td><td align="right">2016-02-26 15:23  </td><td align="right">  - </td><td>&nbsp;</td></tr>\n<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="rpm-hammer/">rpm-hammer/</a>            </td><td align="right">2016-02-26 14:59  </td><td align="right">  - </td><td>&nbsp;</td></tr>\n   <tr><th colspan="5"><hr></th></tr>\n</table>\n</body></html>\n'}
DEBUG: ConnMan.put(): connection put back to pool (https://ceph-101-181#1)
ERROR: Error parsing xml: syntax error: line 1, column 54
ERROR: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
<head>
  <title>Index of /</title>
</head>
<body>
<h1>Index of /</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>
   <tr><th colspan="5"><hr></th></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="keys/">keys/</a>                  </td><td align="right">2016-02-26 15:23  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="rpm-hammer/">rpm-hammer/</a>            </td><td align="right">2016-02-26 14:59  </td><td align="right">  - </td><td>&nbsp;</td></tr>
   <tr><th colspan="5"><hr></th></tr>
</table>
</body></html>


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/usr/bin/s3cmd' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
DEBUG: Unicodising 'ls' using UTF-8
Invoked as: /usr/bin/s3cmd --debug ls
Problem: ParseError: syntax error: line 1, column 54
S3cmd:   1.6.1
python:   2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 291, in list_all_buckets
    response["list"] = getListFromXml(response["data"], "Bucket")
  File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 101, in getListFromXml
    tree = getTreeFromXml(xml)
  File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 89, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 54
```
hope the above debug log is helpful! I still uncertain whether this problem was caused by wrong configuration or software bug. 

Anyhow, look forward to hearing from you!

**Comment by fviard** [comment]
When looking at the debug reply, you can see that the server is serving some html content, but not "S3" xml. So are you sure that the "host" address that you use is right for your s3 gateway? like that the s3 gateway is listening on port 80 or 443 and not on another one like 443?

**Comment by lzw06061139** [comment]
@fviard , thank you for yr reply. yes, this issue cased by misconfiguration. Im running s3 gateway on Apache(default listening on 80) and FastCGI, while I configured s3cmd tool with "using https",on default it's listening on 443.by the way, it's the output should be more graceful in this circumstance。
