### ISSUE TITLE
error: [Errno 113] No route to host

### ISSUE THREAD

**Issue by clemyvi** [s3tools/s3cmd#731]
I'm getting the following error when I run s3cmd ls

I don't understand what is going on as I was able to run both put and get commands successfully prior to this.

Invoked as: /usr/local/bin/s3cmd ls
Problem: error: [Errno 113] No route to host
S3cmd:   1.6.1
python:   2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2919, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2841, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 124, in cmd_ls
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 129, in subcmd_all_buckets_list
  File "build/bdist.linux-armv7l/egg/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "build/bdist.linux-armv7l/egg/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "build/bdist.linux-armv7l/egg/S3/ConnMan.py", line 192, in get
    conn.c.connect()
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 113] No route to host

**Comment by fviard** [comment]
Are you still able to do the "put" and "get" and not the "ls"?
does a "s3cmd ls s3://name_one_bucket/" work?
If yes, maybe your "host_base" is not well setup?

**Comment by clemyvi** [comment]
I think the problem does not come from s3cmd. When this problem happened I was using a 3G dongle, that was behaving weirdly. When I plugged the ethernet cable in my pi, I couldn't reproduce the error.

**Comment by Satoshi-Nakamoto-Dev** [comment]
$ npm install -g vsce
$ vsce package
$ code --install-extension markdown-fenced-codeblock-example-injection-0.0.1.vsix
