### ISSUE TITLE
Problem: UnboundLocalError: local variable 'conn' referenced before assignment

### ISSUE THREAD

**Issue by plittlefield** [s3tools/s3cmd#738]
Hello,

I upgraded my Ubuntu Linux from 12.04 to 14.04 and I am now getting this bug.

Strangely, just s3cmd --help works, but anything more than that, gets the same error shown below.

```
$ s3cmd --debug ls
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/home/paully/.s3cfg'
DEBUG: ConfigParser: access_key->AK...17_chars...A
DEBUG: ConfigParser: bucket_location->EU
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: cloudfront_resource->/2010-07-15/distribution
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->em...5_chars...e
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3.amazonaws.com
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3-external-3.amazonaws.com
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->4096
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: secret_key->gp...37_chars...Y
DEBUG: ConfigParser: send_chunk->4096
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->10
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'ls' using UTF-8
DEBUG: Command: ls
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Tue, 10 May 2016 12:09:57 +0000\n/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(None): s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://s3.amazonaws.com
DEBUG: Using ca_certs_file None
DEBUG: Recognized AWS S3 host, disabling initial SSL hostname check
DEBUG: httplib.HTTPSConnection() has neither context nor check_hostname
DEBUG: non-proxied HTTPSConnection(s3.amazonaws.com)
DEBUG: Unicodising '/usr/local/bin/s3cmd' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
DEBUG: Unicodising 'ls' using UTF-8
Invoked as: /usr/local/bin/s3cmd --debug ls
Problem: UnboundLocalError: local variable 'conn' referenced before assignment
S3cmd:   1.6.1
python:   2.7.11 (default, Dec 14 2015, 22:56:59)
[GCC 4.6.3]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2919, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2841, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 124, in cmd_ls
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 129, in subcmd_all_buckets_list
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 1106, in send_request
    conn.counter = ConnMan.conn_max_counter
UnboundLocalError: local variable 'conn' referenced before assignment
```

I hope you can help.

Thanks,

Paul Littlefield

**Comment by romantolkachyov** [comment]
MacOS fails too.

```
Invoked as: /Users/roman/work/.envs/fastgate/bin/s3cmd -c /Users/roman/.s3cfg.riak_cs du
Problem: UnboundLocalError: local variable 'conn' referenced before assignment
S3cmd:   1.6.1
python:   2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
environment LANG=ru_RU.UTF-8

Traceback (most recent call last):
  File "/Users/roman/work/.envs/fastgate/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/Users/roman/work/.envs/fastgate/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/Users/roman/work/.envs/fastgate/bin/s3cmd", line 67, in cmd_du
    subcmd_bucket_usage_all(s3)
  File "/Users/roman/work/.envs/fastgate/bin/s3cmd", line 75, in subcmd_bucket_usage_all
    response = s3.list_all_buckets()
  File "/Users/roman/work/.envs/fastgate/lib/python2.7/site-packages/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "/Users/roman/work/.envs/fastgate/lib/python2.7/site-packages/S3/S3.py", line 1106, in send_request
    conn.counter = ConnMan.conn_max_counter
UnboundLocalError: local variable 'conn' referenced before assignment
```

**Comment by plittlefield** [comment]
I have fixed my problem with the correct version of Python for the
particular version of Ubuntu Linux.

**Comment by fviard** [comment]
A fix was added to master, you should not encounter this error anymore that was hiding another possible issue.
Don't hesitate to try again with the latest version of master, and if there is still an issue with your setup, we should be able to have a correct trace of the problem.
