### ISSUE TITLE
s3cmd CertificateError although names match

### ISSUE THREAD

**Issue by edwintorok** [s3tools/s3cmd#741]
s3cmd tries to validate the hostname against `amazonaws.com` even though I use a custom S3 server (LibreS3) in `host_base`/`host_bucket`.

I have to use `--no-check-hostname` as a workaround. This is a new problem, older versions of s3cmd used to work fine:

```
$ s3cmd -c libres3.s3cfg ls --debug
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file 'libres3.s3cfg'
DEBUG: ConfigParser: access_key->ed...15_chars...m
DEBUG: ConfigParser: bucket_location->US
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->12...6_chars... 
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3.indian.skylable.com:8443
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.indian.skylable.com:8443
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->4096
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: secret_key->3m...53_chars...A
DEBUG: ConfigParser: send_chunk->4096
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: ConfigParser: ca_certs_file->/home/edwin/skylable/libres3.pem
DEBUG: Updating Config.Config cache_file -> 
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'ls' using UTF-8
DEBUG: Command: ls
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Wed, 11 May 2016 12:00:34 +0000\n/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(None): s3.indian.skylable.com:8443
DEBUG: ConnMan.get(): creating new connection: https://s3.indian.skylable.com:8443
DEBUG: Using ca_certs_file /home/edwin/skylable/libres3.pem
DEBUG: httplib.HTTPSConnection() has only context
DEBUG: non-proxied HTTPSConnection(s3.indian.skylable.com:8443)
DEBUG: checking SSL subjectAltName against amazonaws.com

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/usr/lib/python-exec/python2.7/s3cmd' using UTF-8
DEBUG: Unicodising '-c' using UTF-8
DEBUG: Unicodising 'libres3.s3cfg' using UTF-8
DEBUG: Unicodising 'ls' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
Invoked as: /usr/lib/python-exec/python2.7/s3cmd -c libres3.s3cfg ls --debug
Problem: CertificateError: hostname 's3.indian.skylable.com:8443' doesn't match either of '*.s3.indian.skylable.com', 's3.indian.skylable.com'
S3cmd:   1.6.1
python:   2.7.11 (default, Apr 29 2016, 22:13:09) 
[GCC 5.3.0]
environment LANG=en_US.utf8

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/lib/python-exec/python2.7/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/lib/python-exec/python2.7/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/lib/python-exec/python2.7/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib64/python2.7/site-packages/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "/usr/lib64/python2.7/site-packages/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/usr/lib64/python2.7/site-packages/S3/ConnMan.py", line 194, in get
    conn.match_hostname()
  File "/usr/lib64/python2.7/site-packages/S3/ConnMan.py", line 111, in match_hostname
    self.match_hostname_aws(cert, e)
  File "/usr/lib64/python2.7/site-packages/S3/ConnMan.py", line 100, in match_hostname_aws
    raise e
CertificateError: hostname 's3.indian.skylable.com:8443' doesn't match either of '*.s3.indian.skylable.com', 's3.indian.skylable.com'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

$ python2 --version
Python 2.7.11
```

**Comment by mdomsch** [comment]
It seems to be failing the string match due to the :8443 appended to the
hostname.  I bet the match_hostname() set of functions needs to explicitly
strip off the :port portion.

**Comment by mastachand** [comment]
Any plans for a fix on this?

**Comment by fviard** [comment]
I just pushed in master a fix for this issue.
Now, everything should work well for everyone regarding certificate validations I hope.
@edwintorok @mastachand Can I ask you to give a try to the last master to see if your problem are solved?
Thanks
