### ISSUE TITLE
Problem: TypeError: expected string or buffer(1.6.1)

### ISSUE THREAD

**Issue by rny** [s3tools/s3cmd#744]
works in s3cmd version 1.6.0
failed in s3cmd version 1.6.1

"cn-north-1" region, changed as the FAQ says:

https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions#7-problem-s3cmd-not-working-with-a-bucket-in-the-cn-north-1-region

```
ubuntu@ip-10-0-0-8:~$ s3cmd ls

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd ls
Problem: TypeError: expected string or buffer
S3cmd:   1.6.1
python:   2.7.11+ (default, Apr 17 2016, 14:00:29)
[GCC 5.3.1 20160413]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 1117, in send_request
    return self._http_400_handler(request, response, self.send_request, request)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 1045, in _http_400_handler
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 1077, in send_request
    method_string, resource, headers = request.get_triplet()
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 199, in get_triplet
    self.sign()
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 188, in sign
    if not check_bucket_name_dns_support(self.s3.config.host_bucket, self.resource['bucket']):
  File "/usr/lib/python2.7/dist-packages/S3/Utils.py", line 452, in check_bucket_name_dns_support
    return check_bucket_name(bucket_name, dns_strict = True)
  File "/usr/lib/python2.7/dist-packages/S3/Utils.py", line 410, in check_bucket_name
    invalid = re.search("([^a-z0-9\.-])", bucket, re.UNICODE)
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by fviard** [comment]
Thanks, there is a bug, you are right.
I will have a look at it.

**Comment by fviard** [comment]
After an initial debugging session, it looks like that this issue impact all the servers that supports only signature_v4.
So same issue with frankfurt.

**Comment by fviard** [comment]
@rny that should be fixed in "master" now.
Please, can you give it a try? Thanks

**Comment by rny** [comment]
Yes, It works now!

i tested in the following steps:

```
lunch a new ubuntu server 14.04 in aws CN region.

git clone https://github.com/s3tools/s3cmd.git
cd s3cmd/
sudo python setup.py install
sudo ln -s /usr/local/bin/s3cmd /usr/bin/s3cmd
s3cmd --configure
vim /home/ubuntu/.s3cfg
s3cmd ls
2015-11-09 09:53  s3://xxxxxxxxx

```
