### ISSUE TITLE
Problem: ValueError: unsupported format character '.' (0x2e) at index 3

### ISSUE THREAD

**Issue by zuker** [s3tools/s3cmd#75]
If a "%" symbol in gpg_passpharse is used getting this error:

Problem: ValueError: unsupported format character '.' (0x2e) at index 3
S3cmd:   1.0.0

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2006, in <module>
    main()
  File "/usr/bin/s3cmd", line 1795, in main
    cfg = Config(options.config)
  File "/usr/share/s3cmd/S3/Config.py", line 88, in **init**
    self.read_config_file(configfile)
  File "/usr/share/s3cmd/S3/Config.py", line 105, in read_config_file
    cp = ConfigParser(configfile)
  File "/usr/share/s3cmd/S3/Config.py", line 142, in **init**
    self.parse_file(file, sections)
  File "/usr/share/s3cmd/S3/Config.py", line 170, in parse_file
    print_value = (data["value"][:2]+"...%d_chars..."+data["value"][-1:]) % (len(data["value"]) - 3)
ValueError: unsupported format character '.' (0x2e) at index 3

**Comment by fviard** [comment]
Closing old ticket. Issue already resolved in current version.
