### ISSUE TITLE
Config.py conflicts between old and new versions

### ISSUE THREAD

**Issue by kchitrapu** [s3tools/s3cmd#760]
First I hit an s3tools installation error on OS X which probably left some files around in /Library/Python/2.7/site-packages/S3/. Installed s3tools in my home directory using `pip install --user`. Now s3cmd gave `etag` key error. @harshavardhana suggested to update s3tools which I installed using `pip install --user` again. The updated s3cmd version had signature changes to `Config()` which conflicted with Config.py of the first failed installation.
## Expected behaviour

```
# s3cmd 
Usage: s3cmd [options] COMMAND [parameters]
...
```
## Actual behaviour

```
$ s3cmd

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /Users/foo/Library/Python/2.7/bin/s3cmd
Problem: TypeError: __new__() takes at most 4 arguments (5 given)
S3cmd:   1.6.1
python:   2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/Users/foo/Library/Python/2.7/bin/s3cmd", line 2920, in <module>
    rc = main()
  File "/Users/foo/Library/Python/2.7/bin/s3cmd", line 2654, in main
    cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
TypeError: __new__() takes at most 4 arguments (5 given)
```
## Steps to reproduce the behaviour

On Mac with El Captain:

```
$ sudo pip install --ignore-installed six s3cmd
...
  creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-4iA1aq/s3cmd/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ny6Hb7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-4iA1aq/s3cmd/

$ sudo pip install --user s3cmd
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->s3cmd)
Installing collected packages: s3cmd
  Running setup.py install for s3cmd ... done
Successfully installed s3cmd
...
$ s3cmd --no-ssl get s3://gama/k8s.config 
download: 's3://gama/k8s.config' -> './k8s.config'  [1 of 1]
 10231 of 10231   100% in    0s  1727.99 kB/s  done

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /Users/kchitrapu//Library/Python/2.7/bin/s3cmd --no-ssl get s3://gama/k8s.config
Problem: KeyError: 'etag'
S3cmd:   1.6.1

$ rm -rf /Users/kchitrapu//Library/Python/2.7

$ pip install --user git+https://github.com/s3tools/s3cmd.git@4f07fea9df2fe5b0ed7cfacb50be4291a611bb6f

```
## Version

```
$ s3cmd --version
s3cmd version 1.6.1
```
## System information

```
$ uname -a
Darwin C02M32RZFD58.local 15.5.0 Darwin Kernel Version 15.5.0
```

**Comment by fviard** [comment]
I think that you should have 2 versions of s3cmd installed.
I'm not expert in mac, but I guess that there should be a version installed inside a python "system" dir?
Have you checked in the "/Library/Python/2.7/site-packages" folder for any "S3" dir? (Not the user space one, the one at the root). Less important, but you should have a "s3cmd"python/binary installed somewhere in a binary dir. In Linux it would be in a place like /usr/bin/

After a complete cleanup, and reinstall, I think that it should work for you.
