### ISSUE TITLE
UnicodeDecodeError Exception '--exclude-from [file]' (with s3cmd 1.6.1)

### ISSUE THREAD

**Issue by doodoori2** [s3tools/s3cmd#797]
```
Invoked as: ~/s3cmd/s3cmd-1.6.1/s3cmd sync --exclude-from=.s3cmdignore ~ s3://[s3_bucket]
Problem: UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 0: ordinal not in range(128)
S3cmd:   1.6.1
python:   2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
environment LANG=ko_KR.UTF-8

Traceback (most recent call last):
  File "~/s3cmd/s3cmd-1.6.1/s3cmd", line 2919, in <module>
    rc = main()
  File "~/s3cmd/s3cmd-1.6.1/s3cmd", line 2773, in main
    patterns_list, patterns_textual = process_patterns(options.exclude, options.exclude_from, is_glob = True, option_txt = "exclude")
  File "~/s3cmd/s3cmd-1.6.1/s3cmd", line 2325, in process_patterns
    patterns_list = process_patterns_from_file(fname, patterns_list)
  File "~/s3cmd/s3cmd-1.6.1/s3cmd", line 2302, in process_patterns_from_file
    debug(u"%s: adding rule: %s" % (fname, pattern))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 0: ordinal not in range(128)

$ cat .s3cmdignore
휴지통
```

It looks like 'exclude-from file' can't handle unicode text.

**Comment by fviard** [comment]
Thank you for your detailed report, this should now be fixed in Master.
