### ISSUE TITLE
Problem: IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by morochosve** [s3tools/s3cmd#799]
was configurated .s3cfg and after give me that : 

[root@localhost ~]# s3cmd ls

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd ls
Problem: IOError: [Errno 2] No such file or directory
S3cmd:   1.6.1
python:   2.7.11 (default, Sep 29 2016, 13:33:00)
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/usr/lib/python2.7/site-packages/S3/ConnMan.py", line 191, in get
    conn = http_connection(conn_id, hostname, ssl, cfg)
  File "/usr/lib/python2.7/site-packages/S3/ConnMan.py", line 161, in __init__
    self.c = http_connection._https_connection(hostname)
  File "/usr/lib/python2.7/site-packages/S3/ConnMan.py", line 117, in _https_connection
    context = http_connection._ssl_context()
  File "/usr/lib/python2.7/site-packages/S3/ConnMan.py", line 66, in _ssl_context
    context = http_connection._ssl_verified_context(cafile)
  File "/usr/lib/python2.7/site-packages/S3/ConnMan.py", line 34, in _ssl_verified_context
    context = ssl.create_default_context(cafile=cafile)
  File "/usr/lib64/python2.7/ssl.py", line 435, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
IOError: [Errno 2] No such file or directory

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Could you paste here the configuration that you use? (without access/secret keys)
