### ISSUE TITLE
Error in --cf-invalidate

### ISSUE THREAD

**Issue by cyno** [s3tools/s3cmd#8]
I get the following error using --cf-invalidate with the current s3cmd code :

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: KeyError: 'S3Origin'
S3cmd:   1.1.0-beta1

Traceback (most recent call last):
  File "/usr/bin/s3cmd-beta", line 1790, in <module>
    main()
  File "/usr/bin/s3cmd-beta", line 1732, in main
    cmd_func(args)
  File "/usr/bin/s3cmd-beta", line 965, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/bin/s3cmd-beta", line 955, in cmd_sync_local2remote
    result = cf.InvalidateObjects(uri, uploaded_objects_list)
  File "/usr/share/s3cmd-beta/S3/CloudFront.py", line 428, in InvalidateObjects
    cfuri = self.get_dist_name_for_bucket(uri)
  File "/usr/share/s3cmd-beta/S3/CloudFront.py", line 556, in get_dist_name_for_bucket
    CloudFront.dist_list[getBucketFromHostname(d.info['S3Origin']['DNSName'])[0]] = d.uri()
KeyError: 'S3Origin'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Should already be fixed now!
