### ISSUE TITLE
gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by Dhuran** [s3tools/s3cmd#831]
Sometimes we received an error when trying to use command(uploading files to Amazon S3):
`s3cmd put -rv source s3://bucket/directory`

**The Error**:
`Invoked as: /usr/bin/s3cmd ls s3://bucket_name/directory/
Problem: gaierror: [Errno -2] Name or service not known
S3cmd:   1.6.1
python:   2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 120, in cmd_ls
    subcmd_bucket_list(s3, uri)
  File "/usr/bin/s3cmd", line 153, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 297, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params):
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 324, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 343, in bucket_list_noparse
    response = self.send_request(request)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/usr/lib/python2.7/dist-packages/S3/ConnMan.py", line 192, in get
    conn.c.connect()
  File "/usr/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net`

**Configuration file**:
[default]
access_key = ***
access_token =
add_encoding_exts =
add_headers =
bucket_location = EU
ca_certs_file =
cache_file =
check_ssl_certificate = True
cloudfront_host = cloudfront.amazonaws.com
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
expiry_date =
expiry_days =
expiry_prefix =
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase =
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
ignore_failed_copy = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
limitrate = 0
list_md5 = False
log_target_prefix =
long_listing = False
max_delete = -1
mime_type =
multipart_chunk_size_mb = 15
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
put_continue = False
recursive = False
recv_chunk = 65536
reduced_redundancy = False
requester_pays = False
restore_days = 1
secret_key = ***
send_chunk = 65536
server_side_encryption = False
signature_v2 = False
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
urlencoding_mode = normal
use_https = False
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error =
website_index = index.html

**s3cmd version**:
`~# s3cmd --version
s3cmd version 1.6.1`

**Comment by Dhuran** [comment]
We have tested our DNS server in the exact same and did not find any problems. Amazon S3 names resolves fine.

**Comment by ofmorescale** [comment]
Hi, I'm having the exact same problem with a very similar configuration file.

Previous proposed solutions didn't fix the problem:
- https://github.com/s3tools/s3cmd/issues/683
- https://github.com/s3tools/s3cmd/issues/748

Please comment if anyone knows what the solution might be.

**Comment by fviard** [comment]
@ofmorescale Did you try the latest MASTER of s3cmd ?
Can you post your configuration file without the access/secret keys?

**Comment by rbrenton** [comment]
I ran into this issue and changed default_region from us-east-1d to us-east-1 to resolve it.
