### ISSUE TITLE
TypeError when providing --access_key and $AWS_ACCESS_KEY_ID but not $AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by PeterJCLaw** [s3tools/s3cmd#875]
When running:
``` shell
export AWS_ACCESS_KEY_ID=blah
s3cmd get --recursive --force s3://stuff/more-stuff/ /tmp/destination/ --access_key=${AWS_ACCESS_KEY_ID}
```
I get the following error:
```
Problem: TypeError: cannot concatenate 'str' and 'NoneType' objects
S3cmd:   1.6.1
python:   2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "/home/peter/.virtualenvs/blah/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/home/peter/.virtualenvs/blah/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/home/peter/.virtualenvs/blah/bin/s3cmd", line 465, in cmd_object_get
    remote_list, exclude_list, remote_total_size = fetch_remote_list(args, require_attribs = False)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/FileLists.py", line 455, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/FileLists.py", line 392, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/S3.py", line 297, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params):
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/S3.py", line 324, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/S3.py", line 343, in bucket_list_noparse
    response = self.send_request(request)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/S3.py", line 1077, in send_request
    method_string, resource, headers = request.get_triplet()
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/S3.py", line 199, in get_triplet
    self.sign()
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/S3.py", line 195, in sign
    bucket_region, self.headers, self.body)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/Crypto.py", line 143, in sign_string_v4
    signing_key = getSignatureKey(secret_key, datestamp, region, service)
  File "/home/peter/.virtualenvs/blah/local/lib/python2.7/site-packages/S3/Crypto.py", line 86, in getSignatureKey
    kDate = sign(encode_to_s3('AWS4' + key), dateStamp)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

This seems to be caused by the combination of `--access_key` and `$AWS_ACCESS_KEY_ID` since removing `--access_key` and adding the (admittedly entirely missing) `$AWS_SECRET_ACCESS_KEY` to the environment makes the command work.

Ideally `s3cmd` should emit a nice error explaining to the user that they've missed out an argument rather than crashing.

**Comment by fviard** [comment]
Thank you, good catch!
I'm looking at fixing the access/secret keys config and so will have that fixed in a few days.

**Comment by lundstrj** [comment]
Did this ever get resolved?
