### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 93: ordinal not in range(128)

### ISSUE THREAD

**Issue by mgla** [s3tools/s3cmd#884]
I having the following error with s3cmd, latest from git (as well as v1.6.1.):

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /root/s3cmd/s3cmd -v --no-check-md5 sync /my/folder/a/b/c/ s3://[redacted] --delete-removed
Traceback (most recent call last):
  File "/root/s3cmd/s3cmd", line 3076, in <module>
    report_exception(e)
  File "/root/s3cmd/s3cmd", line 2947, in report_exception
    sys.stderr.write(u"Problem: %s: %s\n" % (e_class, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 93: ordinal not in range(128)
```

I can reproduce it, but the file is most one of about a million I am trying to sync - and I have not idea which one.

Any suggestions?

Edit, run with -d:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /root/s3cmd/s3cmd -d -v --no-check-md5 sync / /my/folder/a/b/c/ s3://[redacted] --delete-removed
Traceback (most recent call last):
  File "/root/s3cmd/s3cmd", line 3076, in <module>
    report_exception(e)
  File "/root/s3cmd/s3cmd", line 2947, in report_exception
    sys.stderr.write(u"Problem: %s: %s\n" % (e_class, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 93: ordinal not in range(128)
```

**Comment by fviard** [comment]
Can you run the command with the -d flag to have more logs?
On what system are you running s3cmd?
Is there non ascii characters in your path (local or remote?) and maybe in your files names?

**Comment by mgla** [comment]
@fviard I updated the original Issue with the debug run. I am running on a Linux 3.2.0-4-amd64 kernel, Debian wheezy, Python 2.7.3.

I am currently trying to narrow down which file causes the issue.

**Comment by fviard** [comment]
@mgla With the "-d" option, what would be interesting is a few lines before the backtrace/error, so we can see what was being done/on which file? (if names of the files are confidential, at least you can identify the special characters inside)
