### ISSUE TITLE
ValueError: insecure string pickle

### ISSUE THREAD

**Issue by aamche** [s3tools/s3cmd#900]
I've not been able to find a solution to this. Some folders in /var/www/* work and some don't. I'm guessing possibly an encoding issue at this stage.

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

From s3cmd
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd sync /var/www/[redacted]/data/ s3://[redacted]/data/ --config=/var/scripts/s3-backup/.s3cfg --cache-file=/var/scripts/s3-backup/cache/www.cache/[redacted].cache --delete-removed --recursive -d -v
Problem: ValueError: insecure string pickle
S3cmd:   1.6.1
python:   2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2962, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2884, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1818, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/local/bin/s3cmd", line 1792, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/usr/local/bin/s3cmd", line 1550, in _single_process
    return _child(destination_base, source_args)
  File "/usr/local/bin/s3cmd", line 1635, in _child
    local_list, single_file_local, src_exclude_list, local_total_size = fetch_local_list(args[:-1], is_src = True, recursive = True)
  File "/var/scripts/s3-backup/bin/s3cmd-master/S3/FileLists.py", line 315, in fetch_local_list
    cache.load(cfg.cache_file)
  File "/var/scripts/s3-backup/bin/s3cmd-master/S3/HashCache.py", line 59, in load
    d = pickle.load(f)
ValueError: insecure string pickle

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by fviard** [comment]
@aamche I did push some fixes related to the loading of cache. Is it possible for you to give a try to the last MASTER to see if you are still able to reproduce your issue?
It might be possible that you would have to "rm" your existing cache file

**Comment by aamche** [comment]
Seems to be working as expected. Sorry about the slow reply, let it run and forgot to reply.
