### ISSUE TITLE
s3cmd uploads fail when using --cf-invalidate

### ISSUE THREAD

**Issue by johnmarkschofield** [s3tools/s3cmd#918]
```
s3cmd --check-md5 --no-preserve --delete-removed --mime-type="text/html" --guess-mime-type --cf-invalidate --cf-invalidate-default-index --add-header="Cache-Control:max-age=604800" sync output/ s3://schof.org/
upload: 'output/sitemap.xml' -> 's3://schof.org/sitemap.xml'  [1 of 1]
 48738 of 48738   100% in    0s   138.61 kB/s  done
Done. Uploaded 48738 bytes in 1.0 seconds, 47.60 kB/s.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /Users/schof/.virtualenvs/schof.org/bin/s3cmd --check-md5 --no-preserve --delete-removed --mime-type=text/html --guess-mime-type --cf-invalidate --cf-invalidate-default-index --add-header=Cache-Control:max-age=604800 sync output/ s3://schof.org/
Problem: TypeError: 'module' object is not callable
S3cmd:   2.0.0
python:   2.7.12 (default, Oct 11 2016, 05:24:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/Users/schof/.virtualenvs/schof.org/bin/s3cmd", line 2996, in <module>
    rc = main()
  File "/Users/schof/.virtualenvs/schof.org/bin/s3cmd", line 2915, in main
    rc = cmd_func(args)
  File "/Users/schof/.virtualenvs/schof.org/bin/s3cmd", line 1837, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/Users/schof/.virtualenvs/schof.org/bin/s3cmd", line 1817, in cmd_sync_local2remote
    _invalidate_on_cf(destination_base_uri)
  File "/Users/schof/.virtualenvs/schof.org/bin/s3cmd", line 1786, in _invalidate_on_cf
    results = cf.InvalidateObjects(destination_base_uri, uploaded_objects_list, default_index_file, cfg.invalidate_default_index_on_cf, cfg.invalidate_default_index_root_on_cf)
  File "/Users/schof/.virtualenvs/schof.org/lib/python2.7/site-packages/S3/CloudFront.py", line 468, in InvalidateObjects
    debug("InvalidateObjects(): request_body: %s" % invalbatch)
  File "/Users/schof/.virtualenvs/schof.org/lib/python2.7/site-packages/S3/CloudFront.py", line 289, in __str__
    s3 = S3(Config())
TypeError: 'module' object is not callable

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by johnmarkschofield** [comment]
Also note this mailing list message, which describes the same problem on FreeBSD:

[](https://sourceforge.net/p/s3tools/mailman/message/35835353/)

**Comment by johnmarkschofield** [comment]
Sadly, PEBKAC. Works when I run it from the command-line; fails when I run it from my fabric file.
