### ISSUE TITLE
File upload issue: ad Content-Type header value: 'text/x-fortranapplication/octet-stream'

### ISSUE THREAD

**Issue by rhysmeister** [s3tools/s3cmd#962]
Hello,

I am using s3cmd to syncronise Cassandra snapshots to s3 and I get the following error on certain files. It's seems to have some type of issue with a particular file...

> ERROR: Error parsing xml: syntax error: line 1, column 0
> ERROR: Bad Content-Type header value: 'text/x-fortranapplication/octet-stream'

This is one specific table in the backup. Thousands of other files are uploaded without any isue. The full traceback (redacted) is as follows...

> [user@cassandra_host TEST ~]$ /usr/bin/s3cmd --no-check-md5 --server-side-encryption -c /home/user/.s3cfg_ sync /path/to/cassandra/data/db/myTable-a0283e40126c11e8b79457600e6b9f77/snapshots/20180406/ s3://stbwmsz-casm03/20180406/snapshot/path/to/cassandra/data/db/myTable-a0283e40126c11e8b79457600e6b9f77/snapshots/20180406/
> upload: '/path/to/cassandra/data/db/myTable-a0283e40126c11e8b79457600e6b9f77/snapshots/20180406/lb-58-big-Data.db' -> 's3://stbwmsz-casm03/20180406/snapshot/path/to/cassandra/data/db/myTable-a0283e40126c11e8b79457600e6b9f77/snapshots/20180406/lb-58-big-Data.db'  [1 of 16]
>  477 of 477   100% in    0s     7.10 kB/s  done
> ERROR: Error parsing xml: syntax error: line 1, column 0
> ERROR: Bad Content-Type header value: 'text/x-fortranapplication/octet-stream'
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>     An unexpected error has occurred.
>   Please try reproducing the error using
>   the latest s3cmd code from the git master
>   branch found at:
>     https://github.com/s3tools/s3cmd
>   and have a look at the known issues list:
>     https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
>   If the error persists, please report the
>   following lines (removing any private
>   info as necessary) to:
>    s3tools-bugs@lists.sourceforge.net
> 
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Invoked as: /usr/bin/s3cmd --no-check-md5 --server-side-encryption -c /home/user/.s3cfg_ sync /path/to/cassandra/data/db/myTable-a0283e40126c11e8b79457600e6b9f77/snapshots/20180406/ s3://stbwmsz-casm03/20180406/snapshot/path/to/cassandra/data/db/myTable-a0283e40126c11e8b79457600e6b9f77/snapshots/20180406/
> Problem: ParseError: syntax error: line 1, column 0
> S3cmd:   2.0.1
> python:   2.7.5 (default, May  3 2017, 07:55:04) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
> environment LANG=en_US.UTF-8
> 
> Traceback (most recent call last):
>   File "/usr/bin/s3cmd", line 3073, in <module>
>     rc = main()
>   File "/usr/bin/s3cmd", line 2989, in main
>     rc = cmd_func(args)
>   File "/usr/bin/s3cmd", line 1873, in cmd_sync
>     return cmd_sync_local2remote(args)
>   File "/usr/bin/s3cmd", line 1846, in cmd_sync_local2remote
>     ret = _single_process(args[:-1])
>   File "/usr/bin/s3cmd", line 1605, in _single_process
>     return _child(destination_base, source_args)
>   File "/usr/bin/s3cmd", line 1769, in _child
>     ret, n, size_transferred = _upload(local_list, 0, upload_count, size_transferred)
>   File "/usr/bin/s3cmd", line 1661, in _upload
>     response = s3.object_put(src, uri, extra_headers, extra_label = seq_label)
>   File "/usr/lib/python2.7/site-packages/S3/S3.py", line 707, in object_put
>     response = self.send_file(request, src_stream, labels)
>   File "/usr/lib/python2.7/site-packages/S3/S3.py", line 1502, in send_file
>     self.send_file, request, stream, labels, buffer, offset = offset, chunk_size = chunk_size, use_expect_continue = use_expect_continue)
>   File "/usr/lib/python2.7/site-packages/S3/S3.py", line 1174, in _http_400_handler
>     failureCode = getTextFromXml(response['data'], 'Code')
>   File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 141, in getTextFromXml
>     tree = getTreeFromXml(xml)
>   File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 105, in getTreeFromXml
>     tree = ET.fromstring(xml)
>   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
>     parser.feed(text)
>   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
>     self._raiseerror(v)
>   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
>     raise err
> ParseError: syntax error: line 1, column 0
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>     An unexpected error has occurred.
>   Please try reproducing the error using
>   the latest s3cmd code from the git master
>   branch found at:
>     https://github.com/s3tools/s3cmd
>   and have a look at the known issues list:
>     https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
>   If the error persists, please report the
>   above lines (removing any private
>   info as necessary) to:
>    s3tools-bugs@lists.sourceforge.net
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I am using the latest release;

> linux> s3cmd --version
> s3cmd version 2.0.1
> linux> python --version
> Python 2.7.5

Any clue as to what mmight be going on here? I am uploading to a thirdy-party s3 compatible storage.

Rhys

**Comment by fviard** [comment]
I think that there is an issue with your third party server or configuration.
s3cmd is complaining because the response from the server doesn't look like a valid s3 xml response.

You can run the command with the "-d" flag to have a log more details and see exactly what is sent back by the server to understand.
Also, from the error message i also guess a server issue because:
text/x-fortranapplication/octet-stream
does look like a mix of 2 content types:
text/x-fortran   and application/octet-stream.

**Comment by rhysmeister** [comment]
Hi,
Had to add the full --debug flag to get this output....

[REDACTED]

> DEBUG: Using signature v2
> DEBUG: SignHeaders: u'PUT\n\ntext/x-fortranapplication/octet-stream\n\nx-amz-date:Mon, 09 Apr 2018 09:05:25 +0000\nx-amz-meta-s3cmd-attrs:atime:1523225115/ctime:1523224813/gid:510/gname:cass/mode:33188/mtime:1522713614/uid:510/uname:cass\nx-amz-server-side-encryption:AES256\nx-amz-storage-class:STANDARD\n/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> DEBUG: get_hostname(XXXXXXXXXXX): XXXXXXXXXXXXXXXXXX
> DEBUG: ConnMan.get(): re-using connection: XXXXXXXXXXXXXXXXXXXXXXX
> DEBUG: format_uri(): /path/to/cassandra//data/db/table/snapshots/20180409/XXXXXX.db
>  477 of 477   100% in    0s   583.00 kB/sDEBUG: ConnMan.put(): connection put back to pool (https://XXXXXXXXXXXXXXXXXXXXXXXX)
> DEBUG: Response:
> {'data': "Bad Content-Type header value: 'text/x-fortranapplication/octet-stream'",
>  'headers': {'content-type': 'text/plain',
>              'date': 'Mon, 09 Apr 2018 09:05:25 GMT',
>              'transfer-encoding': 'chunked'},
>  'reason': 'Bad Request',
>  'size': 477,
>  'status': 400}
>  477 of 477   100% in    0s     9.72 kB/s  done
> ERROR: Error parsing xml: syntax error: line 1, column 0
> ERROR: Bad Content-Type header value: 'text/x-fortranapplication/octet-stream'

This looks like to me s3cmd is adding the dodgy mime type. In fact if I add the --no-guess-mime-type or --no-mime-magic flgas the upload works. I can see --no-guess-mime-type goes with whatever the default MIME type is set. What does --no-mime-magic  do precisely?

I've checked a few of the Cassandra db files to see what the MIME type was set to. Most of them seem to be application/octet-stream although I did find a couple with image/x-icon.

Cheers,

Rhys

**Comment by rhysmeister** [comment]
I don't have the mimetype utility installed but file returns "FORTRAN programdata". This is the only file across a 6 node cluster  (approx 6K files) that is identified as such.

**Comment by rhysmeister** [comment]
Mmm, ok...

`file --mime-type -b  /path/to/cassandra//data/db/table/snapshots/20180409/XXXXXX.db`

returns...

text/x-fortranapplication/octet-stream

**Comment by fviard** [comment]
Can you do file --version to know what version do you have?
it is curious, but it looks like that its file mime type database that have an issue.
There are multiple versions of mime-magic but in your case i think that it will use the python default lib that will use "file" one.

**Comment by rhysmeister** [comment]
file --version
file-5.11
magic file from /etc/magic:/usr/share/misc/magic

**Comment by fviard** [comment]
ok, it is quite old.
You should try to update if you can.
Is it possible for you to do a kind of empty cassandra db, or some minimal file that you can share?
I can try file on that, i have file-5.25 and if it is still there, you should probably open an issue on file/shared mime types

**Comment by rhysmeister** [comment]
I'm working in quite a locked down corporate environment so probably not. I'm on training the next couple of days but will follow up when I return. Thanks for your assistance so far.

Rhys

**Comment by fviard** [comment]
No problem, anyway, if it is just to target these cassandra db, and that you don't care about the mime-type, just use the "no-mime-magic" flag.
And if you care, but you just have the db, you have a flag to manually set the "mime-type" that you want to be reported.

**Comment by rhysmeister** [comment]
On stretch/sid
> ~$ file --version
> file-5.25
> magic file from /etc/magic:/usr/share/misc/magic
> ~$ file lb-58-big-Data.db 
> lb-58-big-Data.db: data
> ~$ file --mime-type lb-58-big-Data.db 
> lb-58-big-Data.db: application/octet-stream

So more than likely due to an old version of file then. I'm probably being over fussy but I'll probably get it updated. 

Thanks again for the help.

Rhys
