### ISSUE TITLE
Failuer to install the latest master on Ubuntu-14.04

### ISSUE THREAD

**Issue by igoratencompass** [s3tools/s3cmd#963]
I get the following error when try to install the latest master:

```
# git clone https://github.com/s3tools/s3cmd.git .
# python setup.py install
Using xml.etree.ElementTree for XML processing
running install
running bdist_egg
running egg_info
writing requirements to s3cmd.egg-info/requires.txt
writing s3cmd.egg-info/PKG-INFO
writing top-level names to s3cmd.egg-info/top_level.txt
writing dependency_links to s3cmd.egg-info/dependency_links.txt
reading manifest file 's3cmd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 's3cmd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/S3.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Custom_httplib27.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/PkgInfo.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Config.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Custom_httplib3x.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/HashCache.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Exceptions.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/S3Uri.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/AccessLog.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/FileLists.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Crypto.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/ExitCodes.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/ConnMan.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Utils.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/__init__.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/SortedDict.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/FileDict.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/ACL.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/Progress.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/MultiPart.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/BidirMap.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib.linux-x86_64-2.7/S3/CloudFront.py -> build/bdist.linux-x86_64/egg/S3
byte-compiling build/bdist.linux-x86_64/egg/S3/S3.py to S3.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Custom_httplib27.py to Custom_httplib27.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/PkgInfo.py to PkgInfo.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Config.py to Config.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Custom_httplib3x.py to Custom_httplib3x.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/HashCache.py to HashCache.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Exceptions.py to Exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/S3Uri.py to S3Uri.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/AccessLog.py to AccessLog.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/FileLists.py to FileLists.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Crypto.py to Crypto.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/ExitCodes.py to ExitCodes.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/ConnMan.py to ConnMan.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Utils.py to Utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/SortedDict.py to SortedDict.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/FileDict.py to FileDict.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/ACL.py to ACL.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Progress.py to Progress.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/MultiPart.py to MultiPart.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/BidirMap.py to BidirMap.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/CloudFront.py to CloudFront.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/doc
creating build/bdist.linux-x86_64/egg/share/doc/packages
creating build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying README.md -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying INSTALL -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying LICENSE -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying NEWS -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
creating build/bdist.linux-x86_64/egg/share/man
creating build/bdist.linux-x86_64/egg/share/man/man1
copying s3cmd.1 -> build/bdist.linux-x86_64/egg/share/man/man1
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/s3cmd -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/s3cmd to 755
copying s3cmd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/s3cmd-2.0.1_-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing s3cmd-2.0.1_-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/s3cmd-2.0.1_-py2.7.egg
Copying s3cmd-2.0.1_-py2.7.egg to /usr/local/lib/python2.7/dist-packages
s3cmd 2.0.1- is already the active version in easy-install.pth
Installing s3cmd script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/s3cmd-2.0.1_-py2.7.egg
Processing dependencies for s3cmd==2.0.1-
Searching for python-dateutil
Reading https://pypi.python.org/simple/python-dateutil/
Best match: python-dateutil 2.7.2
Downloading https://pypi.python.org/packages/c5/39/4da7c2dbc4f023fba5fb2325febcadf0d0ce0efdc8bd12083a0f65d20653/python-dateutil-2.7.2.tar.gz#md5=03a08c8bcf0a2b29f1cd21b9de4d12fb
Processing python-dateutil-2.7.2.tar.gz
Writing /tmp/easy_install-meVZTA/python-dateutil-2.7.2/setup.cfg
Running python-dateutil-2.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-meVZTA/python-dateutil-2.7.2/egg-dist-tmp-VB6HhO
/tmp/easy_install-meVZTA/python-dateutil-2.7.2/setup.py:19: UserWarning: python_requires requires setuptools version > 24.3
  UserWarning)
Searching for setuptools-scm
Reading https://pypi.python.org/simple/setuptools_scm/
Best match: setuptools-scm 2.0.0
Downloading https://pypi.python.org/packages/2d/0c/90c42717d075b02d8503949ff0a4e4ca6bc0577db0ccd43a801500c0b7d5/setuptools_scm-2.0.0-py2.7.egg#md5=cfb06336f8a97451c7dbd43fbb2f99f4
Processing setuptools_scm-2.0.0-py2.7.egg
Moving setuptools_scm-2.0.0-py2.7.egg to /tmp/easy_install-meVZTA/python-dateutil-2.7.2

Installed /tmp/easy_install-meVZTA/python-dateutil-2.7.2/setuptools_scm-2.0.0-py2.7.egg
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 112, in <module>
    install_requires = ["python-dateutil", "python-magic"]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 86, in <module>
    
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/easy_install-meVZTA/python-dateutil-2.7.2/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/integration.py", line 10, in version_keyword
  File "/tmp/easy_install-meVZTA/python-dateutil-2.7.2/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/version.py", line 44, in _warn_if_setuptools_outdated
setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
```
Not sure what the issue exactly is but the `setuptools` version it is complaining about and requires `python_requires requires setuptools version > 24.3` is definitely satisfied:
```
# pip list local | grep tools
setuptools (39.0.1)
```
The OS:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by fviard** [comment]
@igoratencompass Hum, based on your log, it looks like that it is not directly an issue coming from s3cmd, but from a bug/regression in setuptools-scm.
So, s3cmd just requires the python-dateutil package, that itself requires the package setuptools_scm that looks to be broken.

You might try to install setuptools_scm / dateutils yourself before installing s3cmd.
In my opinion, you could try to install an older version of setuptools_scm.
I don't know anything about it, but at least I see a suspicious change in their version 2.0.0:
https://github.com/pypa/setuptools_scm/blob/master/CHANGELOG.rst
<<"breaking change: remove support for setuptools before parsed versions>>

**Comment by ctaymor** [comment]
I ran into the same problem. I was able to switch to using pip to install s3cmd instead however, with 
```
sudo apt-get install python-pip
sudo pip install s3cmd
```

**Comment by sujun1992** [comment]
I have the same problem. Did you solve this problem at the end?

**Comment by fviard** [comment]
In case someone encounters the issue, there is a solution proposed there:
https://github.com/s3tools/s3cmd/issues/979#issuecomment-472506285
