### ISSUE TITLE
Check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED

### ISSUE THREAD

**Issue by MRinalducci** [s3tools/s3cmd#965]
Hi,

I have the following issue which was previously corrected with this [issue](https://github.com/s3tools/s3cmd/issues/769).

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/csw/bin/s3cmd ls
Problem: <class 'ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
S3cmd:   2.0.1+
python:   3.3.2 (default, Jul 28 2013, 17:43:07)
[GCC 4.8.0]
Traceback (most recent call last):
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/EGG-INFO/scripts/s3cmd", line 3080, in <module>
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/EGG-INFO/scripts/s3cmd", line 2996, in main
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/EGG-INFO/scripts/s3cmd", line 144, in cmd_ls
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/EGG-INFO/scripts/s3cmd", line 149, in subcmd_all_buckets_list
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/S3/S3.py", line 301, in list_all_buckets
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/S3/S3.py", line 1251, in send_request
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/S3/ConnMan.py", line 252, in get
  File "/opt/csw/lib/python3.3/site-packages/s3cmd-2.0.1_-py3.3.egg/S3/ConnMan.py", line 206, in __init__
  File TypeError ", line 163, in _https_connection
  File "/opt/csw/lib/python3.3/http/client.py", line 1183, in __init__
    raise ValueError("check_hostname needs a SSL context with "
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```

It seems that the type of error has changed from `TypeError` to `ValueError` in Python HTTP Client.

https://github.com/python/cpython/blob/942cc04ae44825ea120e3a19a80c9b348b8194d0/Lib/http/client.py#L1268-L1270

I tested changing  `TypeError` to `ValueError` on line 165 and 170 and it is resolving this error/issue.

https://github.com/s3tools/s3cmd/blob/d07bcfa6e151ee485931288106f4f9078fea5100/S3/ConnMan.py#L161-L174

**Comment by fviard** [comment]
Thank you very much for the investigation, I will try to integrate that as a fix.

**Comment by MRinalducci** [comment]
You welcome!
Maybe catch both exceptions for backwards compatibility.
Thank you :)

**Comment by fviard** [comment]
i tried everything but I'm not able to reproduce this with all set of ssl options.
So I'm not sure to what happened in your case.
I guess and hope that it is resolved.
Please reopen if you are still encountering this issue with the MASTER or the next release (>2.0.2).

**Comment by fviard** [comment]
btw, I looked at the exception thing.
The catch for TypeError si something else.
We try to handle old python that had not the same set of arguments for the function.
But your case is strange, you should not arrive in a case where you encounter this ValueError.
