### ISSUE TITLE
Problem: <class 'TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by HyperDevil** [s3tools/s3cmd#967]
S3cmd:   2.0.1
python:   3.6.5 (default, Apr 14 2018, 13:17:30)
[GCC 7.3.1 20180406]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 1316, in _download
    response = s3.object_get(uri, dst_stream, dst_file, extra_label = seq_label)
  File "/usr/lib/python3.6/site-packages/S3/S3.py", line 715, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "/usr/lib/python3.6/site-packages/S3/S3.py", line 1612, in recv_file
    http_response = conn.c.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/site-packages/S3/Custom_httplib3x.py", line 53, in httpresponse_patched_begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3073, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1875, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1470, in cmd_sync_remote2local
    ret, seq, size_transferred = _download(remote_list, seq, remote_count + update_count, size_transferred, dir_cache)
  File "/usr/bin/s3cmd", line 1347, in _download
    error(u"Download of '%s' failed (Reason: Unknown OsError %d)" % (file, exc.errno))
TypeError: %d format: a number is required, not NoneType

**Comment by HyperDevil** [comment]
This is towards AWS S3 service.

**Comment by fviard** [comment]
Thank you very much for the report.
For the second part of the exception, this is related to that issue:
https://github.com/s3tools/s3cmd/issues/960

I'm investigating that, but i'm a little puzzled because python3 is not doing what is says it should do :-s

**Comment by fviard** [comment]
@HyperDevil With a fix that I did for #960, I hope that your issue should now be fixed with the last MASTER version.
