### ISSUE TITLE
setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

### ISSUE THREAD

**Issue by m2cci-KGY** [s3tools/s3cmd#979]
Hi guys, I setup the package of  setuptools_scm with this commands "sudo python setup.py install"
but i have this error.
first all, I download the packages of setuptools version 31 which I installed but when I'm intalling the packages of setuptools_scm  again I have the same error.
I need your help please.

/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    setuptools.setup(**arguments)
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
    ep.load()(self, ep.name, value)
  File "/opt/SHINKEN_DEV_DEPOT/setuptools_scm-2.1.0/setuptools_scm/integration.py", line 10, in version_keyword
    _warn_if_setuptools_outdated()
  File "/opt/SHINKEN_DEV_DEPOT/setuptools_scm-2.1.0/setuptools_scm/version.py", line 44, in _warn_if_setuptools_outdated
    warnings.warn("your setuptools is too old (<12)", SetuptoolsOutdatedWarning)

Thank you for yours help

**Comment by fviard** [comment]
Your issue is the same as this one: https://github.com/s3tools/s3cmd/issues/963
I'm annoyed by this, but I don't really know what we can do, it looks like that it is because of something that was broken in a sub package of setuptools and that setuptools was updated in ubuntu repo.
And this is required by python-dateutils that we are using. And maybe it is python-dateutils that was not updated.

So I'm not sure, if someone needs to complain to the python-dateutils team or to ubuntu maintainers of setuptools_scm.

**Comment by m2cci-KGY** [comment]
I don't use use Ubuntu but my os is redaht

**Comment by m2cci-KGY** [comment]
Please help me to fix my problem

**Comment by fviard** [comment]
Have you seen the solution proposed in #963?

> sudo apt-get install python-pip
> sudo pip install s3cmd

It is a little bit dirty, but pip should be able to bring you more recent dependencies.
replace apt-get install by the quivalent yum install command for red hat

**Comment by m2cci-KGY** [comment]
I haven't access to internet connexion with my server wich I installed my package 
so I Installed the all packages with the sources.

**Comment by pabloacera** [comment]
Does it work after this

`pip install --upgrade setuptools pip`

**Comment by Damini17** [comment]
Hey, 
I faced this issue and got the error when I was trying to install appiumLibrary using pip. I got a possible solution here: https://packaging.python.org/tutorials/installing-packages/#ensure-pip-setuptools-and-wheel-are-up-to-date

setuptools and wheel projects are useful to ensure you can also install from source archives. So you need to install setuptools or upgrade it using this command.

python -m pip install --upgrade pip setuptools wheel

This solved the issue for me and now I have successfully installed appiumLibrary.

**Comment by xiebruce** [comment]
@Damini17 I got the same error, your solution works for me too, thank you!
I just want to tell you guys who got the same error, just run the following command, it will solve your problem:
```
python -m pip install --upgrade pip setuptools wheel
```
