### ISSUE TITLE
set public permissions for 30000 files for digitalocean

### ISSUE THREAD

**Issue by strangerxx** [s3tools/s3cmd#982]
````
Invoked as: /usr/bin/s3cmd setacl s3://greet4you/ --acl-public --recursive
Problem: RemoteDisconnected: Remote end closed connection without response
S3cmd:   2.0.1
python:   3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]
environment LANG=ru_RU.UTF-8
Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3073, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1921, in cmd_setacl
    update_acl(s3, uri, seq_label)
  File "/usr/bin/s3cmd", line 2525, in update_acl
    acl = s3.get_acl(uri)
  File "/usr/lib/python3.6/site-packages/S3/S3.py", line 938, in get_acl
    response = self.send_request(request)
  File "/usr/lib/python3.6/site-packages/S3/S3.py", line 1256, in send_request
    http_response = conn.c.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/site-packages/S3/Custom_httplib3x.py", line 53, in httpresponse_patched_begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
````

**Comment by fviard** [comment]
@strangerxx Can you give a try to the last github MASTER version?
There is a fix for having retries in such a situation.
It was directed at aws s3 that has a very strange behavior, so if it is the same cause it should be fixed.

**Comment by strangerxx** [comment]
@fviard Ok, try and write

**Comment by strangerxx** [comment]
@fviard Git version work normal, but where update in repository archlinux?

**Comment by fviard** [comment]
A new official release 2.2.0 is out, and I have flagged the package in Arch linux, so that it could be updated there too soon.
